Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2018-11, with the labels that each got.

#629 Enable aks
  Jenkinsfile_CNP
  kubernetes/deployment.template.yaml
Labels: ns:sscs-tribunals-frontend-pr-629

#632 Fix default evidence upload URL
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-632

#634 Remove text from NotAttending step
  steps/hearing/not-attending/content.en.json
  steps/hearing/not-attending/template.html
Labels: ns:sscs-tribunals-frontend-pr-634

#640 Revert "MRN thirteen months late point to DWP office step"
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs-tribunals-frontend-pr-640

#641 Revert "Revert "MRN thirteen months late point to DWP office step""
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs-tribunals-frontend-pr-641

#642 Added line breaks to the readme for testing purposes
  README.md
Labels: ns:sscs-tribunals-frontend-pr-642

#645 Added readiness probe to AKS
  kubernetes/deployment.template.yaml
Labels: ns:sscs-tribunals-frontend-pr-645

#644 UnRevert "MRN thirteen months late point to DWP…
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs-tribunals-frontend-pr-644

#638 Move Appointee question to before contact details
  steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/no-mrn/NoMRN.js
  steps/identity/appointee/Appointee.js
  steps/start/postcode-checker/PostcodeChecker.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeESA.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/no-mrn/NoMRN.test.js
  test/unit/steps/identity/appointee/Appointee.test.js
  test/unit/steps/start/PostcodeChecker.test.js
Labels: ns:sscs-tribunals-frontend-pr-638

#647 update to content
  steps/start/postcode-checker/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-647
