Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-07, with the labels that each got.

#788 SSCS-5565 fix glasgow , fix node engine version.
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  package.json
Labels: ns:sscs-tribunals-frontend-pr-788

#789 Node version
  infrastructure/main.tf
Labels: ns:sscs-tribunals-frontend-pr-789

#790 Change dependency types.
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-790

#791 Adding nunkjucks
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-791

#793 Node version10
  Dockerfile
  infrastructure/main.tf
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-793

#795 Previous version of opp.
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-795

#796 upgrade node version to latests on azure
  infrastructure/main.tf
  package.json
  server.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-796

#798 Expand event listener and node version 8.11.1
  Dockerfile
  app.js
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-798

#799 OPP 5.0.1
  package.json
  views/components/globals.html
  webpack/webpack.common.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-799

#800 Add contact us to every question page.
  appConfigurations.js
  config/custom-environment-variables.json
  config/default.json
  content.en.json
  infrastructure/variables.tf
  steps/check-your-appeal/template.html
  steps/compliance/contact-dwp/template.html
  steps/reasons-for-appealing/evidence-provide/template.html
  steps/reasons-for-appealing/evidence-upload/template.html
  steps/reasons-for-appealing/other-reasons-for-appealing/template.html
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/benefit-type/template.html
  steps/start/independence/template.html
  views/components/contact-us.html
  views/components/globals.html
  views/layouts/question.html
  views/layouts/two_thirds.html
Labels: ns:sscs-tribunals-frontend-pr-800

#804 SSCS-5725 Donot check postcode if blank
  test/unit/utils/postcodeChecker.test.js
  utils/postcodeChecker.js
Labels: ns:sscs-tribunals-frontend-pr-804

#803 Sscs 5123 web form
  appConfigurations.js
  config/custom-environment-variables.json
  config/default.json
  content.en.json
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  views/components/contact-us.html
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-803

#802 Adding new signout feature
  assets/scss/main.scss
  middleware/draftAppealStoreMiddleware.js
  middleware/idam.js
  paths.js
  steps.js
  steps/idam/sign-out/SignOut.js
  steps/idam/sign-out/content.en.json
  steps/idam/sign-out/template.html
  test/accessibility/a11y.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/middleware/idam.test.js
  test/unit/steps/idam/SignOut.test.js
  views/layouts/question.html
Labels: ns:sscs-tribunals-frontend-pr-802

#806 SSCS-6170 Seperate webconfig from app start.
  Jenkinsfile_CNP
  package.json
  server.js
Labels: ns:sscs-tribunals-frontend-pr-806

#805 SSCS-6103 Update image location to hmctspublic
  Dockerfile
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
  charts/sscs-tribunals-frontend/values.yaml
  services/health.js
Labels: ns:sscs-tribunals-frontend-pr-805
