Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-04, with the labels that each got.

#726 [SSCS-5255] - Fix footer link display and added privacy-policy and contact us page.
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-726

#715 Remove session timeout message from everypage and display it on speci…
  content.en.json
  steps/appeal-form-download/template.html
  steps/check-your-appeal/template.html
  steps/compliance/cant-appeal/template.html
  steps/reasons-for-appealing/evidence-provide/template.html
  steps/reasons-for-appealing/evidence-upload/template.html
  steps/reasons-for-appealing/other-reasons-for-appealing/template.html
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/independence/template.html
  steps/start/invalid-postcode/template.html
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-715

#713 HTML entities encode for title
  config/default.json
  package.json
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/appointee/appointee-contact-details/answer.html
  steps/appointee/appointee-name/AppointeeName.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/compliance/mrn-over-thirteen-months-late/template.html
  steps/hearing/arrangements/HearingArrangements.js
  steps/hearing/arrangements/answer.html
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/answer.html
  steps/identity/appellant-name/AppellantName.js
  steps/reasons-for-appealing/other-reasons-for-appealing/OtherReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/answer.html
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/answer.html
  utils/stringUtils.js
  utils/titlesList.js
  views/components/formElements.html
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-713

#731 Backend and this.journey.values integration for save and return
  app.js
  middleware/draftAppealStoreMiddleware.js
  steps/idam/authenticated/Authenticated.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-tribunals-frontend-pr-731

#729 display 'complete your appeal' on CYA after login
  steps/idam/authenticated/Authenticated.js
  steps/idam/idam-redirect/IdamRedirect.js
  test/unit/steps/idam/Authenticated.test.js
  test/unit/steps/idam/IdamRedirect.test.js
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-tribunals-frontend-pr-729

#733 [SSCS-5421] Change Save draft to put and, handle not ready req.journey.values.
  middleware/draftAppealStoreMiddleware.js
Labels: ns:sscs-tribunals-frontend-pr-733

#732 [SSCS-5240] Add a pixel image for no javascript tracking.
  assets/images/noJS.png
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-732

#737 Sscs 5419 2
  middleware/draftAppealStoreMiddleware.js
  package.json
  steps/entry/Entry.js
  steps/idam/authenticated/Authenticated.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/idam/Authenticated.test.js
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-tribunals-frontend-pr-737

#739 fix issues with smoke test
  infrastructure/preview.tfvars
  test/config.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs-tribunals-frontend-pr-739

#740 Task/sscs 5508 fix smoke test
  infrastructure/preview.tfvars
  kubernetes/deployment.template.yaml
  test/config.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs-tribunals-frontend-pr-740

#734 SSCS-5494 - create helm charts
  Jenkinsfile_CNP
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.template.yaml
Labels: ns:sscs-tribunals-frontend-pr-734
