Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-02, with the labels that each got.

#697 Removed old preview environment
  infrastructure/main.tf
  infrastructure/preview.tfvars
Labels: ns:sscs-tribunals-frontend-pr-697

#696 SSCS-4795 Intermittent failure when uploading evidence
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
Labels: ns:sscs-tribunals-frontend-pr-696

#700 Button text on Reasons for appealing page
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-700

#698 Upgrade libraries to latest version
  package.json
  steps/check-your-appeal/selectors.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-698

#704 Added additional app insights logging for 500 error.
  steps/check-your-appeal/CheckYourAppeal.js
Labels: ns:sscs-tribunals-frontend-pr-704

#705 Freeze `applicationinsights` version
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-705

#706 Upgrade appinsights packages from 1.03 to 1.1 and make the new Errror…
  package.json
  test/unit/logger.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-706

#682 Phone number validation poc
  package.json
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/content.en.json
  steps/sms-notify/enter-mobile/EnterMobile.js
  utils/customJoiSchemas.js
  utils/regex.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-682

#707 exclude test mock and static content
  package.json
Labels: ns:sscs-tribunals-frontend-pr-707

#708 Fix product/component split
  Jenkinsfile_CNP
  logger.js
Labels: ns:sscs-tribunals-frontend-pr-708

#709 Add `yarn test:audit` package vulnerability testing to the build and nightly pipelines
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-709
