Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-10, with the labels that each got.

#852 Fix logout and missing esa content
  appConfigurations.js
  steps/compliance/have-a-mrn/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-852

#854 SSCS-6703
  steps/idam/sign-out/SignOut.js
  steps/idam/sign-out/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-854

#850 Fix Vulnerabilities
  policy-pages/accessibility/template.html
  policy-pages/contact-us/template.html
  views/components/contact-us.html
Labels: ns:sscs-tribunals-frontend-pr-850

#849 Add content to create account page.
  steps/start/create-account/content.en.json
  steps/start/create-account/template.html
Labels: ns:sscs-tribunals-frontend-pr-849

#855 Turn on save and return flag.
  Jenkinsfile_CNP
  infrastructure/prod.tfvars
Labels: ns:sscs-tribunals-frontend-pr-855

#857 Bugfix/sscs 6724 ver2
  middleware/idam.js
  package.json
  paths.js
  steps.js
  steps/idam/sign-in-back/SignInBack.js
  steps/idam/sign-out/SignOut.js
  steps/idam/sign-out/content.en.json
  test/accessibility/a11y.js
  test/unit/middleware/idam.test.js
Labels: ns:sscs-tribunals-frontend-pr-857

#847 Update fileupload whitelist.
  steps/reasons-for-appealing/evidence-upload/fileTypeWhitelist.js
Labels: ns:sscs-tribunals-frontend-pr-847

#858 SSCS-6731 - Revert back signout button display from app level to page level.
  appConfigurations.js
  middleware/draftAppealStoreMiddleware.js
  steps/start/independence/Independence.js
Labels: ns:sscs-tribunals-frontend-pr-858

#859 Fix log issue for file upload.
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  test/unit/middleware/EvidenceUpload.test.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs-tribunals-frontend-pr-859

#862 redirect to benefit type page.
  steps/idam/idam-redirect/IdamRedirect.js
  steps/start/create-account/CreateAccount.js
  test/unit/steps/idam/IdamRedirect.test.js
Labels: ns:sscs-tribunals-frontend-pr-862

#861 Disable form buttons form 1 sec to prevent double tapping.
  assets/js/main.js
  steps/idam/idam-redirect/IdamRedirect.js
  test/unit/steps/idam/IdamRedirect.test.js
Labels: ns:sscs-tribunals-frontend-pr-861

#863 Skip create account page if the user is already loggedin.
  steps/start/create-account/CreateAccount.js
  steps/start/independence/Independence.js
Labels: ns:sscs-tribunals-frontend-pr-863

#865 remove whitelist from reasonForNoMRN field
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
Labels: ns:sscs-tribunals-frontend-pr-865

#866 Remove whitelist regex from evidence description.
  steps/reasons-for-appealing/evidence-description/EvidenceDescription.js
Labels: ns:sscs-tribunals-frontend-pr-866

#867 remove whitelist from hearing arrangments.
  steps/hearing/arrangements/HearingArrangements.js
Labels: ns:sscs-tribunals-frontend-pr-867

#869 Remove whitelist from sendtosame number field.
  steps/sms-notify/send-to-number/SendToNumber.js
Labels: ns:sscs-tribunals-frontend-pr-869

#868 Add word to whitelist for file upload
  steps/reasons-for-appealing/evidence-upload/fileTypeWhitelist.js
Labels: ns:sscs-tribunals-frontend-pr-868

#871 SSCS-6730 Feature/sscs 6730 npe
  middleware/draftAppealStoreMiddleware.js
  package.json
  steps/idam/idam-redirect/IdamRedirect.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/idam/IdamRedirect.test.js
  test/unit/steps/idam/SignInBack.test.js
Labels: ns:sscs-tribunals-frontend-pr-871
