Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-08, with the labels that each got.

#801 SSCS-5122 web chat
  appConfigurations.js
  assets/scss/main.scss
  config/custom-environment-variables.json
  config/default.json
  content.en.json
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  test/accessibility/a11y.js
  views/components/contact-us.html
  views/components/globals.html
  webpack/webpack.common.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-801

#807 Update survey links
  appConfigurations.js
  steps/compliance/cant-appeal/template.html
  steps/compliance/contact-dwp/template.html
  steps/confirmation/template.html
  steps/errors/500/Error500.html
  steps/errors/Error404.html
  steps/exit-points/session-timeout/template.html
  steps/idam/sign-out/template.html
  steps/start/benefit-type/template.html
  urls.js
  views/components/globals.html
  views/components/phase_banner.njk
  views/layouts/check_your_answers.html
  views/layouts/error.html
  views/layouts/question.html
Labels: ns:sscs-tribunals-frontend-pr-807

#808 Sscs 6296 web chat prod values
  content.en.json
  infrastructure/prod.tfvars
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-808

#809 Webchat button parameters
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-809

#810 Add missing parameter.
  infrastructure/variables.tf
Labels: ns:sscs-tribunals-frontend-pr-810

#812 Fix JSA type.
  steps/start/benefit-type/template.html
Labels: ns:sscs-tribunals-frontend-pr-812

#811 Enable universal credit.
  config/custom-environment-variables.json
  config/default.json
  steps/start/benefit-type/BenefitType.js
Labels: ns:sscs-tribunals-frontend-pr-811

#814 Enable uc flag for aat.
  config/default.json
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-tribunals-frontend-pr-814

#815 remove deprecated config
  Jenkinsfile_CNP
Labels: ns:sscs-tribunals-frontend-pr-815

#818 Fix autocomplete for benefit types.
  assets/js/main.js
Labels: ns:sscs-tribunals-frontend-pr-818

#822 SSCS-6401 UC copy showing on PIP appeals
  steps/compliance/contact-dwp/ContactDWP.js
  steps/compliance/contact-dwp/template.html
  steps/compliance/have-contacted-dwp/HaveContactedDWP.js
  steps/compliance/have-contacted-dwp/template.html
  test/unit/steps/compliance/contact-dwp/ContactDWP.test.js
  test/unit/steps/compliance/have-contacted-dwp/HaveContactedDWP.test.js
Labels: ns:sscs-tribunals-frontend-pr-822

#823 Improving code coverage - sonar fail
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/Independence.test.js
Labels: ns:sscs-tribunals-frontend-pr-823

#820 SSCS-6249 - Skipping DWP Issuing office page for UC benefit
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs-tribunals-frontend-pr-820

#819 SSCS-6339 - Change mrn image for universal credit.
  assets/images/mrn-date-uc.png
  steps/compliance/check-mrn/CheckMRN.js
  steps/compliance/check-mrn/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-date/template.html
  test/unit/steps/compliance/check-mrn/CheckMRN.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
Labels: ns:sscs-tribunals-frontend-pr-819

#824 SSCS-6248 You still can appeal page
  paths.js
  steps.js
  steps/compliance/no-mrn/NoMRN.js
  steps/compliance/still-can-appeal/StillCanAppeal.js
  steps/compliance/still-can-appeal/content.en.json
  steps/compliance/still-can-appeal/template.html
  test/e2e/journeys/noMRN.test.js
  test/e2e/page-objects/compliance/stillCanAppeal.js
  test/unit/steps/compliance/no-mrn/NoMRN.test.js
  test/unit/steps/compliance/still-can-appeal/StillCanAppeal.test.js
Labels: ns:sscs-tribunals-frontend-pr-824

#821 SSCS-6403 - Csp headers and inline javascript fix and safe html fix
  appConfigurations.js
  assets/js/main.js
  assets/scss/main.scss
  components/postcodeLookup/assets/main.js
  components/postcodeLookup/assets/main.scss
  components/postcodeLookup/template.html
  package.json
  steps/appointee/appointee-contact-details/answer.html
  steps/compliance/cant-appeal/template.html
  steps/compliance/contact-dwp/template.html
  steps/hearing/arrangements/answer.html
  steps/identity/appellant-contact-details/answer.html
  steps/reasons-for-appealing/reason-for-appealing/answer.html
  steps/representative/representative-details/answer.html
  test/assets/postcode-lookup.test.js
  views/components/globals.html
  views/layouts/check_your_answers.html
  views/layouts/question.html
Labels: ns:sscs-tribunals-frontend-pr-821

#825 Fix inline hash for webchat on production
  appConfigurations.js
Labels: ns:sscs-tribunals-frontend-pr-825

#826 Add more policy header for webchat on production.
  appConfigurations.js
Labels: ns:sscs-tribunals-frontend-pr-826

#827 Revert "Add more policy header for webchat on production."
  appConfigurations.js
Labels: ns:sscs-tribunals-frontend-pr-827
