Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-09, with the labels that each got.

#831 Change logo and touch icons.
  appConfigurations.js
  assets/images/hmcts-logo-compress.svg
  assets/images/touch-icons/favicon.ico
  assets/images/touch-icons/hmcts-apple-touch-icon-152x152.png
  assets/images/touch-icons/hmcts-apple-touch-icon-167x167.png
  assets/images/touch-icons/hmcts-apple-touch-icon-180x180.png
  assets/images/touch-icons/hmcts-apple-touch-icon.png
  content.en.json
  views/components/header.njk
  views/components/navigation.html
  views/components/touch-icons.html
  views/layouts/two_thirds.html
Labels: ns:sscs-tribunals-frontend-pr-831

#833 Fix es-lint version for security vulnerability.
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-833

#835 Fix broken sya flow.
  steps/compliance/check-mrn/CheckMRN.js
Labels: ns:sscs-tribunals-frontend-pr-835

#836 Add Label to benefit type drop down.
  assets/js/main.js
Labels: ns:sscs-tribunals-frontend-pr-836

#838 Add whitelisted modules.
  infrastructure/main.tf
Labels: ns:sscs-tribunals-frontend-pr-838

#839 accessibility statement and footer link.
  assets/scss/main.scss
  paths.js
  policy-pages/accessibility/content.en.json
  policy-pages/accessibility/template.html
  policy-pages/routes.js
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-839

#837 DL nesting problem fix.
  assets/js/date-picker/date-picker.js
  policy-pages/accessibility/content.en.json
  policy-pages/accessibility/template.html
  steps/hearing/arrangements/answer.html
  steps/identity/appellant-contact-details/answer.html
  steps/reasons-for-appealing/reason-for-appealing/answer.html
  steps/representative/representative-details/answer.html
  views/components/check-your-answers.njk
  views/layouts/check_your_answers.html
Labels: ns:sscs-tribunals-frontend-pr-837

#840 SSCS-6202
  config/default.json
  package.json
  steps/appointee/appointee-name/AppointeeName.js
  steps/identity/appellant-name/AppellantName.js
  steps/representative/representative-details/RepresentativeDetails.js
  test/unit/steps/appointee/appointee-name/Appointee-name.test.js
  test/unit/steps/identity/appellant-name/AppellantName.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-840

#834 Fix Benefit type dropdowlist when invalid charecter is entered.
  assets/js/main.js
Labels: ns:sscs-tribunals-frontend-pr-834

#816 Have you got mrn page content depending benefit type.
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/have-a-mrn/template.html
Labels: ns:sscs-tribunals-frontend-pr-816

#844 Logout changes.
  appConfigurations.js
  assets/scss/main.scss
  middleware/draftAppealStoreMiddleware.js
  steps/idam/sign-out/SignOut.js
  steps/idam/sign-out/content.en.json
  steps/idam/sign-out/template.html
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/idam/SignOut.test.js
  views/components/navigation.html
  views/layouts/question.html
Labels: ns:sscs-tribunals-frontend-pr-844

#848 turn on UC for production.
  infrastructure/prod.tfvars
Labels: ns:sscs-tribunals-frontend-pr-848
