Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-01, with the labels that each got.

#665 Sscs 4795 intermittent failure uploading evidence
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  test/unit/middleware/EvidenceUpload.test.js
Labels: ns:sscs-tribunals-frontend-pr-665

#667 [SCSS-SSCS-4813]Fixed order of Benefit type dropdown
  steps/start/benefit-type/template.html
Labels: ns:sscs-tribunals-frontend-pr-667

#668 [SSCS-4813] Fix content issues.
  steps/start/benefit-type/template.html
Labels: ns:sscs-tribunals-frontend-pr-668

#670 disclaimer for welsh language
  policy-pages/terms-and-conditions/content.en.json
  policy-pages/terms-and-conditions/template.html
Labels: ns:sscs-tribunals-frontend-pr-670

#666 Re enable ESA
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-666

#672 Revert "Re enable ESA"
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-672

#671 [SSCS-4189] Custom event for google tracking for file size exceeded error in evid…
  assets/js/evidence-upload/evidence-upload.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  test/unit/middleware/EvidenceUpload.test.js
Labels: ns:sscs-tribunals-frontend-pr-671

#673 Revert "Revert "Re enable ESA""
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-673

#674 MRN page accessibility issues
  paths.js
  steps/compliance/have-a-mrn/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-674

#675 Revert "Revert "Revert "Re enable ESA"""
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-675

#676 Revert "Revert "Revert "Revert "Re enable ESA""""
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-676

#678 Optimise docker image build layers
  .dockerignore
  Dockerfile
Labels: ns:sscs-tribunals-frontend-pr-678

#677 Add service name to banner
  assets/scss/main.scss
  views/components/globals.html
Labels: ns:sscs-tribunals-frontend-pr-677

#669 Ask for phone number confirmation on appointee journey
  steps/sms-notify/send-to-number/SendToNumber.js
  steps/sms-notify/sms-confirmation/SmsConfirmation.js
  steps/sms-notify/text-reminders/TextReminders.js
  test/unit/steps/sms-notify/send-to-number/SendToNumber.test.js
  test/unit/steps/sms-notify/sms-confirmation/SmsConfirmation.test.js
  test/unit/steps/sms-notify/text-reminders/TextReminders.test.js
Labels: ns:sscs-tribunals-frontend-pr-669

#679 Testing availability of variables in production
  infrastructure/main.tf
Labels: ns:sscs-tribunals-frontend-pr-679

#680 Copy update for representative details
  steps/representative/representative-details/content.en.json
Labels: ns:sscs-tribunals-frontend-pr-680

#681 SSCS-4795 Intermittent failure when uploading evidence
  app-insights.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  test/unit/middleware/EvidenceUpload.test.js
Labels: ns:sscs-tribunals-frontend-pr-681

#685 SSCS-4795 Intermittent failure when uploading evidence
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
Labels: ns:sscs-tribunals-frontend-pr-685

#683 Enable Appointee Journey
  config/default.json
Labels: ns:sscs-tribunals-frontend-pr-683

#686 Titles validation
  assets/js/main.js
  assets/scss/main.scss
  steps/appointee/appointee-name/AppointeeName.js
  steps/appointee/appointee-name/template.html
  steps/identity/appellant-name/AppellantName.js
  steps/identity/appellant-name/template.html
  utils/titlesList.js
Labels: ns:sscs-tribunals-frontend-pr-686

#688 Revert "Titles validation (#686)"
  assets/js/main.js
  assets/scss/main.scss
  steps/appointee/appointee-name/AppointeeName.js
  steps/appointee/appointee-name/template.html
  steps/identity/appellant-name/AppellantName.js
  steps/identity/appellant-name/template.html
  utils/titlesList.js
Labels: ns:sscs-tribunals-frontend-pr-688

#690 SSCS-4795 Intermittent failure when uploading evidence
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
Labels: ns:sscs-tribunals-frontend-pr-690

#684 [SSCS-4955] Replace nodejs-logger with appinsights logger.
  app-insights.js
  app.js
  config/default.json
  logger.js
  mocks/postcode_checker/index.js
  package.json
  server.js
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/check-your-appeal/CheckYourAppeal.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  steps/start/postcode-checker/BranchForEnglandOrWales.js
  test/e2e/helpers/SauceLabsReportingHelper.js
  test/e2e/saucelabs.conf.js
  test/file_acceptor/evidence_uploader.js
  test/file_acceptor/index.js
  test/unit/middleware/EvidenceUpload.test.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-684

#691 Logger.js Unit Tests
  logger.js
  test/unit/logger.test.js
Labels: ns:sscs-tribunals-frontend-pr-691

#692 Refactor and added more unit test to Logger.js
  test/unit/logger.test.js
Labels: ns:sscs-tribunals-frontend-pr-692

#689 Titles validation
  assets/js/main.js
  assets/scss/main.scss
  steps/appointee/appointee-name/AppointeeName.js
  steps/appointee/appointee-name/template.html
  steps/identity/appellant-name/AppellantName.js
  steps/identity/appellant-name/template.html
  utils/titlesList.js
Labels: ns:sscs-tribunals-frontend-pr-689

#694 SSCS-5043 Logging error caused app outage
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
Labels: ns:sscs-tribunals-frontend-pr-694
