Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-05, with the labels that each got.

#743 remove Create Account section
  Jenkinsfile_CNP
  charts/sscs-tribunals-frontend/values.template.yaml
  kubernetes/deployment.template.yaml
  steps/start/create-account/CreateAccount.js
  test/unit/steps/start/CreateAccount.test.js
Labels: ns:sscs-tribunals-frontend-pr-743

#747 Task/sscs 5519 send null value when no input from user
  steps/sms-notify/send-to-number/SendToNumber.js
  steps/sms-notify/text-reminders/TextReminders.js
  test/unit/steps/sms-notify/send-to-number/SendToNumber.test.js
  test/unit/steps/sms-notify/text-reminders/TextReminders.test.js
Labels: ns:sscs-tribunals-frontend-pr-747

#749 Fix wrong page type for appeal download form page
  steps/appeal-form-download/AppealFormDownload.js
Labels: ns:sscs-tribunals-frontend-pr-749

#753 Adding Scotland Postcodes into SYA - SSCS-4723 - Duplicate PR
  config/default.json
  package.json
  steps/start/postcode-checker/PostcodeChecker.js
  steps/start/postcode-checker/content.en.json
  steps/start/postcode-checker/template.html
Labels: ns:sscs-tribunals-frontend-pr-753

#746 Change Idam landing to create account page SSCS-5521
  config/default.json
  infrastructure/aat.tfvars
  package.json
Labels: ns:sscs-tribunals-frontend-pr-746

#744 Introduce graceful-fs to SYA/TYA frontend
  package.json
  server.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  test/file_acceptor/index.js
  test/unit/middleware/EvidenceUpload.test.js
Labels: ns:sscs-tribunals-frontend-pr-744

#750 Task/sscs 5519 complete happy path response
  steps/hearing/the-hearing/TheHearing.js
  steps/identity/appointee/Appointee.js
  steps/reasons-for-appealing/evidence-provide/EvidenceProvide.js
  steps/representative/representative/Representative.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
  test/unit/steps/identity/appointee/Appointee.test.js
  test/unit/steps/reasons-for-appealing/EvidenceProvide.test.js
  test/unit/steps/representative/representative/Representative.test.js
Labels: ns:sscs-tribunals-frontend-pr-750

#745 Add new postcode lookup component for one per page - SSCS-5366
  app.js
  assets/scss/main.scss
  charts/sscs-tribunals-frontend/values.template.yaml
  components/postcodeLookup/content.en.json
  components/postcodeLookup/controller.js
  components/postcodeLookup/helper.js
  components/postcodeLookup/main.scss
  components/postcodeLookup/template.html
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  package.json
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/template.html
  steps/identity/appellant-nino/AppellantNINO.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/unit/steps/identity/appellant-details/AppellantContactDetails.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-745

#754 Fixing security vulnerabilities
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-754

#758 Revert "Fixing security vulnerabilities"
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-758

#759 Fixing security vulnerabilities (#754)
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-759

#760 Replacing istanbul library for nyc
  .gitignore
  .nycrc
  package.json
Labels: ns:sscs-tribunals-frontend-pr-760

#761 Revert "Replacing istanbul library for nyc"
  .gitignore
  .nycrc
  package.json
Labels: ns:sscs-tribunals-frontend-pr-761

#762 Replacing istanbul library for nyc
  .gitignore
  .nycrc
  package.json
  sonar-project.properties
Labels: ns:sscs-tribunals-frontend-pr-762

#765 Adding known vulnerabilities
  yarn-audit-known-issues
Labels: ns:sscs-tribunals-frontend-pr-765

#764 SSCS-5597 Fix unit test for draftstore middleware.
  middleware/draftAppealStoreMiddleware.js
  package.json
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/logger.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-764

#766 Revert "Replacing istanbul library for nyc (#760) (#762)"
  .gitignore
  .nycrc
  package.json
  sonar-project.properties
Labels: ns:sscs-tribunals-frontend-pr-766

#767 Upgrade Istanbul to Support async.
  .gitignore
  package.json
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-767

#763 Feature/sscs 5574 send null when no input from user yet
  .gitignore
  config/default.json
  steps/appointee/same-address/SameAddress.js
  steps/hearing/availability/HearingAvailability.js
  steps/identity/appointee/Appointee.js
  test/unit/steps/appointee/same-address/Same-address.test.js
  test/unit/steps/hearing/availability/HearingAvailability.test.js
Labels: ns:sscs-tribunals-frontend-pr-763

#768 Change the way security vulnerbilities handled.
  Jenkinsfile_CNP
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-tribunals-frontend-pr-768

#757 Add postcode lookup to representive page
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.template.yaml
  components/postcodeLookup/controller.js
  components/postcodeLookup/customFieldValidations.js
  components/postcodeLookup/template.html
  config/default.json
  infrastructure/prod.tfvars
  mocks/services/idam.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/template.html
  steps/representative/representative/Representative.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/e2e/page-objects/representative/representativeDetails.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/identity/appellant-details/AppellantContactDetails.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
Labels: ns:sscs-tribunals-frontend-pr-757

#769 Postcode Lookup appointee
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/appointee/appointee-contact-details/template.html
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
Labels: ns:sscs-tribunals-frontend-pr-769

#756 Change button text to Save and continue, fix saving on every step SSCS 5523 & SSCS 5525
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.template.yaml
  content.en.json
  infrastructure/aat.tfvars
  middleware/draftAppealStoreMiddleware.js
  package.json
  steps/check-your-appeal/CheckYourAppeal.js
  steps/check-your-appeal/selectors.js
  steps/hearing/dates-cant-attend/DatesCantAttend.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/start/benefit-type/BenefitType.js
  steps/start/create-account/CreateAccount.js
  steps/start/postcode-checker/PostcodeChecker.js
  test/e2e/journeys/noMRN.test.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
  test/unit/steps/start/BenefitType.test.js
  yarn.lock
Labels: ns:sscs-tribunals-frontend-pr-756

#771 Turn on feature flag for postcode lookup
  Jenkinsfile_CNP
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.template.yaml
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
Labels: ns:sscs-tribunals-frontend-pr-771

#770 SSCS-5604 Add user token to submit api call.
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
Labels: ns:sscs-tribunals-frontend-pr-770

#772 fix evidence desc
  steps/reasons-for-appealing/evidence-description/EvidenceDescription.js
  steps/reasons-for-appealing/evidence-description/content.en.json
  test/unit/steps/reasons-for-appealing/EvidenceDescription.test.js
Labels: ns:sscs-tribunals-frontend-pr-772

#773 header cannot be an empty string
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
Labels: ns:sscs-tribunals-frontend-pr-773

#751 SSCS-5494: change helm chart to be consistent
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
Labels: ns:sscs-tribunals-frontend-pr-751

#774 SSCS-5710 adjust postcodelookup for save and return
  components/postcodeLookup/content.en.json
  components/postcodeLookup/controller.js
  components/postcodeLookup/customFieldValidations.js
  components/postcodeLookup/template.html
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/appointee/appointee-contact-details/template.html
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/template.html
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/template.html
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
  test/unit/steps/identity/appellant-details/AppellantContactDetails.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
Labels: ns:sscs-tribunals-frontend-pr-774

#776 SSCS-5598 postcode lookup unit tests and coverage
  components/postcodeLookup/controller.js
  components/postcodeLookup/helper.js
  package.json
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/representative/representative-details/RepresentativeDetails.js
  test/unit/components/postcodeLookup/controller.test.js
  test/unit/components/postcodeLookup/customFieldValidations.test.js
  test/unit/components/postcodeLookup/helper.test.js
Labels: ns:sscs-tribunals-frontend-pr-776
