Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2019-06, with the labels that each got.

#742 Updating sauce to point eu
  test/e2e/helpers/SauceLabsReportingHelper.js
  test/e2e/saucelabs.conf.js
Labels: ns:sscs-tribunals-frontend-pr-742

#778 SSCS-5831 - Add new functional test for postcode lookup.
  test/e2e/data.json
  test/e2e/journeys/manualPostcodeLookup.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/e2e/page-objects/representative/representativeDetails.js
Labels: ns:sscs-tribunals-frontend-pr-778

#779 SSCS-5870 - Adding Worthing DRT to issuing office.
  steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.js
Labels: ns:sscs-tribunals-frontend-pr-779

#780 Task/5913 turn on save return aat
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-tribunals-frontend-pr-780

#784 SSCS-5961 fix save on cya
  middleware/draftAppealStoreMiddleware.js
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs-tribunals-frontend-pr-784

#787 add groovy task to turn off save and return when running smoke tests …
  Jenkinsfile_CNP
Labels: ns:sscs-tribunals-frontend-pr-787
