Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-03, with the labels that each got.

#893 Go live on AKS
  Jenkinsfile_CNP
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-893

#894 Update node.js base chart
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-894

#895 SSCS-6814 SYA - When Rev/Sir/Madam/Mr & Mrs titles are selected the A…
  steps/appointee/appointee-name/AppointeeName.js
  steps/identity/appellant-name/AppellantName.js
  test/unit/steps/appointee/appointee-name/Appointee-name.test.js
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-895

#896 Clearup ASE config
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-896
