Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-08, with the labels that each got.

#957 Add missing Welsh content
  views/layouts/add_another.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-957

#956 WLA-605: SYA e2e
  package.json
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/page-objects/cya/checkYourAnswers.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-956

#941 SSCS-7300: Tech debt – SYA – Migrate to the latest health library and…
  app.js
  appConfigurations.js
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
  config/default.json
  package.json
  services/health.js
  services/healthcheck.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-941

#960 update threadpoolsize from default 4 to 64
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
  package.json
  webpack/webpack.common.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-960

#963 Fixed Sonar issue
  test/unit/steps/reasons-for-appealing/ReasonForAppealing.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-963

#944 PCQ-474: PCQ integration
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  paths.js
  services/setupSecrets.js
  steps.js
  steps/hearing/availability/HearingAvailability.js
  steps/hearing/dates-cant-attend/DatesCantAttend.js
  steps/hearing/not-attending/NotAttendingHearing.js
  steps/pcq/Pcq.js
  steps/pcq/createToken.js
  steps/pcq/template.html
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/pcq/pcq.js
  test/unit/steps/hearing/availability/HearingAvailability.test.js
  test/unit/steps/hearing/dates-cant-attend/DatesCantAttend.test.js
  test/unit/steps/hearing/not-attending/notAttendingHearing.test.js
  test/unit/steps/pcq/Pcq.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-944

#965 SSCS-7895: Investigate and fix dependency checks
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-965

#968 filter tests based on url config
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-968

#970 Fixed security scan issue
  Jenkinsfile_nightly
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-970

#969 Fixed web-chat-issue
  views/components/globals.html
  webpack/webpack.common.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-969

#972 Enable functional tests in SYA nightly build
  Jenkinsfile_nightly
  package.json
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-972

#964 SSCS-7965: SYA – Message if case is already created isn’t working
  steps/errors/duplicate-error/DuplicateError.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-964

#971 Fix security scan 2
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-971

#973 Revert "Fix security scan 2"
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-973

#974 Bkpatel81 patch 1
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-974
