Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-11, with the labels that each got.

#1018 Remove invalid test steps
  config/default.json
  test/e2e/crossbrowser/supportedBrowsers.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1018

#1019 Add wait times for tests
  test/e2e/page-objects/compliance/mrnDate.js
  test/e2e/page-objects/pcq/pcq.js
  test/e2e/page-objects/start/independence.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1019

#1008 updated the privacy policy email in the english and welsh content files
  steps/policy-pages/privacy-policy/content.cy.json
  steps/policy-pages/privacy-policy/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1008

#1020 Add wait for page load
  test/e2e/page-objects/hearing/notAttendingHearing.js
  test/e2e/page-objects/identity/appellantDetails.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1020

#1017 Sscs 8345 remove uc change option video
  appConfigurations.js
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  steps/hearing/the-hearing/TheHearing.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/unit/steps/hearing/options/HearingOptions.test.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1017

#1022 Ignore soncar scan on pcq createtoken
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1022

#1024 Fix sonar issues
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/confirmation/Confirmation.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-dob/AppellantDOB.js
  steps/identity/appellant-name/AppellantName.js
  steps/identity/appellant-nino/AppellantNINO.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1024

#1026 Fix SYA cbt tests
  test/e2e/crossbrowser/supportedBrowsers.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/e2e/page-objects/reasons-for-appealing/reasonForAppealingOnePageForm.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1026

#1027 UPdate webdriver version
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1027

#1028 enable postcode checker tests
  Jenkinsfile_nightly
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/identity/appellantDetails.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1028

#1030 updated config for full functional test
  package.json
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1030

#1032 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1032

#1023 SSCS-8215 Updated address regex
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/appointee/appointee-contact-details/content.cy.json
  steps/appointee/appointee-contact-details/content.en.json
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/content.cy.json
  steps/identity/appellant-contact-details/content.en.json
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/content.cy.json
  steps/representative/representative-details/content.en.json
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
  test/unit/steps/identity/appellant-contact-details/AppellantContactDetails.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
  utils/regex.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1023

#1031 upgrade nodejs chart
  charts/sscs-tribunals-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1031

#1035 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1035

#1034 parallelise SYA functional test
  package.json
  test/e2e/codecept.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1034

#1036 Update tags for nightly tests
  package.json
  test/e2e/journeys/datesCantAttend.cy.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1036

#1033 SSCS-8354:Vulnerabilities and security hotspot to fix in submit your appeal
  package.json
  steps/check-your-appeal/CheckYourAppeal.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  utils/DateUtils.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1033

#1037 fix dates for tests
  package.json
  test/e2e/journeys/datesCantAttend.cy.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1037

#1038 SSCS-8410:Security Hotspot error to fix in SYA
  package.json
  steps/check-your-appeal/CheckYourAppeal.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1038

#1039 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1039

#1040 update audit links
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1040

#1041 SSCS-8432: Hearing Options should not appear when we say NO to attend…
  steps/hearing/the-hearing/TheHearing.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1041

#1042 SSCS-8432: Hearing Options should not appear when we say NO to attend…
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1042

#1045 SSCS-8432: Hearing Options should not appear when we say NO to attend…
  charts/sscs-tribunals-frontend/values.aat.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1045

#1043 Sscs have contacted dwp content changes
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1043

#1048 Fix connect src
  appConfigurations.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1048
