Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-07, with the labels that each got.

#922 WLA-442: Steps Batch 1
  assets/scss/main.scss
  steps/appeal-form-download/AppealFormDownload.js
  steps/appeal-form-download/template.html
  steps/compliance/check-mrn/CheckMRN.js
  steps/compliance/check-mrn/template.html
  steps/compliance/contact-dwp/ContactDWP.js
  steps/compliance/contact-dwp/template.html
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/template.html
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-month-late/template.html
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/compliance/mrn-over-thirteen-months-late/template.html
  steps/start/create-account/CreateAccount.js
  steps/start/create-account/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/template.html
  steps/start/invalid-postcode/InvalidPostcode.js
  steps/start/invalid-postcode/template.html
  steps/start/postcode-checker/PostcodeChecker.js
  steps/start/postcode-checker/template.html
  test/unit/steps/compliance/check-mrn/CheckMRN.test.js
  test/unit/steps/compliance/contact-dwp/ContactDWP.test.js
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/steps/start/CreateAccount.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/steps/start/InvalidPostcode.test.js
  test/unit/steps/start/PostcodeChecker.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-922

#931 update tf version
  infrastructure/.terraform-version
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-931

#932 missing variable
  infrastructure/variables.tf
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-932

#933 Revert "WLA-442: Steps Batch 1"
  assets/scss/main.scss
  steps/appeal-form-download/AppealFormDownload.js
  steps/appeal-form-download/template.html
  steps/compliance/check-mrn/CheckMRN.js
  steps/compliance/check-mrn/template.html
  steps/compliance/contact-dwp/ContactDWP.js
  steps/compliance/contact-dwp/template.html
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/template.html
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-month-late/template.html
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/compliance/mrn-over-thirteen-months-late/template.html
  steps/start/create-account/CreateAccount.js
  steps/start/create-account/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/template.html
  steps/start/invalid-postcode/InvalidPostcode.js
  steps/start/invalid-postcode/template.html
  steps/start/postcode-checker/PostcodeChecker.js
  steps/start/postcode-checker/template.html
  test/unit/steps/compliance/check-mrn/CheckMRN.test.js
  test/unit/steps/compliance/contact-dwp/ContactDWP.test.js
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/steps/start/CreateAccount.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/steps/start/InvalidPostcode.test.js
  test/unit/steps/start/PostcodeChecker.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-933

#936 Remove LD and feature toggles
  .gitignore
  README.md
  appConfigurations.js
  assets/scss/main.scss
  config/a11y.json
  config/default.json
  config/development_template.yaml
  config/test.yaml
  core/components/launch-darkly.js
  core/utils/featureToggle.js
  middleware/checkWelshToggle.js
  middleware/shimSession.js
  package.json
  services/setupSecrets.js
  steps/policy-pages/accessibility/Accessibility.js
  steps/policy-pages/contact-us/ContactUs.js
  steps/policy-pages/cookie-policy/CookiePolicy.js
  steps/policy-pages/privacy-policy/PrivacyPolicy.js
  steps/policy-pages/terms-and-conditions/TermsAndConditions.js
  steps/start/benefit-type/BenefitType.js
  steps/start/independence/Independence.js
  test/e2e/journeys/esa.test.js
  test/e2e/journeys/mrnLate.test.js
  test/e2e/journeys/noMRN.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page/appeal-form-download/appeal-form-download.test.js
  test/e2e/page/check-your-appeal/checkYourAppeal.test.js
  test/e2e/page/start/benefitType.test.js
  test/unit/core/components/launch-darkly.test.js
  test/unit/core/utils/featureToggle.test.js
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/policy-pages/Accessibility.test.js
  test/unit/steps/policy-pages/ContactUs.test.js
  test/unit/steps/policy-pages/CookiePolicy.test.js
  test/unit/steps/policy-pages/PrivacyPolicy.test.js
  test/unit/steps/policy-pages/TermsAndConditions.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/Independence.test.js
  views/components/globals.html
  views/components/phase_banner.njk
  views/layouts/check_your_answers.html
  views/layouts/error.html
  views/layouts/question.html
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-936

#938 SSCS-7782: SYA – Internal server error due to Redis connection
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-938

#939 Fix webchat
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-939

#930 SSCS-7067: SYA – Display message to user if case is already created
  assets/scss/main.scss
  package.json
  paths.js
  steps.js
  steps/check-your-appeal/CheckYourAppeal.js
  steps/errors/duplicate-error/DuplicateError.html
  steps/errors/duplicate-error/DuplicateError.js
  steps/errors/duplicate-error/content.en.json
  test/accessibility/a11y.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
  test/unit/steps/errors/DuplicateError.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-930

#937 SSCS-7768 Add logging and event metrics for missing hearings at CYA
  logger.js
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
  test/unit/steps/logger.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-937

#935 WLA-442: Steps Batch 1
  package.json
  steps/appeal-form-download/template.html
  steps/compliance/check-mrn/template.html
  steps/compliance/contact-dwp/ContactDWP.js
  steps/compliance/contact-dwp/template.html
  steps/compliance/have-a-mrn/template.html
  steps/compliance/mrn-over-month-late/template.html
  steps/compliance/mrn-over-thirteen-months-late/template.html
  steps/start/benefit-type/template.html
  steps/start/create-account/template.html
  steps/start/independence/content.cy.json
  steps/start/independence/template.html
  steps/start/invalid-postcode/template.html
  steps/start/postcode-checker/template.html
  test/unit/steps/compliance/contact-dwp/ContactDWP.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-935

#923 WLA-442: Steps Batch 2
  appConfigurations.js
  assets/js/add-reason.js
  commonContent.json
  components/postcodeLookup/content.cy.json
  components/postcodeLookup/content.en.json
  middleware/draftAppealStoreMiddleware.js
  steps/appointee/appointee-contact-details/answer.html
  steps/appointee/appointee-contact-details/template.html
  steps/appointee/appointee-dob/template.html
  steps/appointee/appointee-name/template.html
  steps/appointee/same-address/template.html
  steps/compliance/cant-appeal/template.html
  steps/compliance/check-mrn/template.html
  steps/compliance/dwp-issuing-office-esa/template.html
  steps/compliance/dwp-issuing-office/template.html
  steps/compliance/have-contacted-dwp/HaveContactedDWP.js
  steps/compliance/have-contacted-dwp/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-date/template.html
  steps/compliance/no-mrn/template.html
  steps/compliance/still-can-appeal/template.html
  steps/hearing/arrangements/content.cy.json
  steps/hearing/availability/template.html
  steps/hearing/support/template.html
  steps/hearing/the-hearing/template.html
  steps/identity/appointee/template.html
  steps/reasons-for-appealing/evidence-provide/template.html
  steps/representative/representative/template.html
  steps/sms-notify/text-reminders/template.html
  steps/start/create-account/template.html
  test/unit/steps/appointee/appointee-contact-details/Appointee-contact-details.test.js
  test/unit/steps/appointee/appointee-name/Appointee-name.test.js
  test/unit/steps/appointee/same-address/Same-address.test.js
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-923

#924 WLA-442: Steps Batch 3
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/answer.html
  steps/identity/appellant-contact-details/template.html
  steps/identity/appellant-dob/template.html
  steps/identity/appellant-name/template.html
  steps/identity/appellant-nino/template.html
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/answer.html
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/representative/no-representative-details/template.html
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/answer.html
  steps/representative/representative-details/template.html
  steps/representative/representative/template.html
  steps/sms-notify/enter-mobile/template.html
  steps/sms-notify/send-to-number/template.html
  steps/sms-notify/sms-confirmation/template.html
  steps/sms-notify/text-reminders/template.html
  test/unit/steps/identity/appellant-contact-details/AppellantContactDetails.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-924

#947 WLA-442: Add Welsh env var
  config/custom-environment-variables.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-947

#948 WLA-442: Set Welsh flag to string
  config/default.json
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/template.html
  steps/start/language-preference/template.html
  test/unit/steps/start/BenefitType.test.js
  views/components/phase_banner.njk
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-948

#925 WLA-442: Steps Batch 4
  package.json
  steps/check-your-appeal/CheckYourAppeal.js
  steps/check-your-appeal/template.html
  steps/compliance/cant-appeal/template.html
  steps/hearing/arrangements/HearingArrangements.js
  steps/hearing/arrangements/answer.html
  steps/hearing/arrangements/cyaHearingArrangementsUtils.js
  steps/hearing/arrangements/template.html
  steps/hearing/availability/template.html
  steps/hearing/dates-cant-attend/DatesCantAttend.js
  steps/hearing/dates-cant-attend/template.html
  steps/hearing/not-attending/template.html
  steps/hearing/support/template.html
  steps/hearing/the-hearing/template.html
  steps/reasons-for-appealing/evidence-description/template.html
  steps/reasons-for-appealing/evidence-provide/template.html
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  steps/reasons-for-appealing/evidence-upload/template.html
  steps/reasons-for-appealing/other-reasons-for-appealing/OtherReasonForAppealing.js
  steps/reasons-for-appealing/other-reasons-for-appealing/template.html
  steps/reasons-for-appealing/sending-evidence/template.html
  test/unit/middleware/EvidenceUpload.test.js
  test/unit/steps/reasons-for-appealing/EvidenceDescription.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-925

#926 WLA-442: Steps Batch 5
  steps/confirmation/template.html
  steps/errors/500/Error500.html
  steps/errors/Error404.html
  steps/exit-points/exit/template.html
  steps/exit-points/session-timeout/template.html
  steps/idam/IdamLogin/template.html
  steps/idam/sign-out/SignOut.js
  steps/idam/sign-out/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-926

#943 WLA-442: Steps Batch 6
  .eslintignore
  assets/js/date-picker/bootstrap-datepicker1.8.0.min.js
  assets/js/date-picker/bootstrap-datepicker1.9.0.min.js
  assets/js/date-picker/date-picker-utils.js
  assets/js/date-picker/date-picker.js
  assets/js/main.js
  components/postcodeLookup/template.html
  steps/appointee/appointee-dob/AppointeeDOB.js
  steps/compliance/check-mrn/CheckMRN.js
  steps/compliance/mrn-date/MRNDate.js
  steps/hearing/dates-cant-attend/DatesCantAttend.js
  steps/hearing/dates-cant-attend/template.html
  steps/identity/appellant-dob/AppellantDOB.js
  steps/start/language-preference/template.html
  test/.eslintrc.json
  test/accessibility/a11y.js
  test/unit/utils/DateUtils.test.js
  test/unit/utils/months.test.js
  utils/DateUtils.js
  utils/months.js
  views/components/fields.njk
  views/layouts/add_another.html
  views/layouts/check_your_answers.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-943

#951 Remove LD Key secret
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-951

#949 WLA-627: Show translated Yes/No on CYA
  appConfigurations.js
  assets/js/add-reason.js
  assets/js/evidence-upload/evidence-upload.js
  steps/appointee/same-address/SameAddress.js
  steps/appointee/same-address/content.cy.json
  steps/appointee/same-address/content.en.json
  steps/confirmation/content.cy.json
  steps/hearing/the-hearing/TheHearing.js
  steps/hearing/the-hearing/content.cy.json
  steps/hearing/the-hearing/content.en.json
  steps/identity/appointee/Appointee.js
  steps/identity/appointee/content.cy.json
  steps/identity/appointee/content.en.json
  steps/reasons-for-appealing/evidence-provide/EvidenceProvide.js
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-provide/content.en.json
  steps/representative/representative/Representative.js
  steps/representative/representative/content.cy.json
  steps/representative/representative/content.en.json
  steps/sms-notify/text-reminders/TextReminders.js
  steps/sms-notify/text-reminders/content.cy.json
  steps/sms-notify/text-reminders/content.en.json
  steps/start/create-account/CreateAccount.js
  steps/start/language-preference/LanguagePreference.js
  steps/start/language-preference/content.cy.json
  steps/start/language-preference/content.en.json
  test/unit/steps/appointee/same-address/Same-address.test.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
  test/unit/steps/identity/appointee/Appointee.test.js
  test/unit/steps/reasons-for-appealing/EvidenceProvide.test.js
  test/unit/steps/representative/representative/Representative.test.js
  test/unit/steps/sms-notify/text-reminders/TextReminders.test.js
  test/unit/steps/start/LanguagePreference.test.js
  views/layouts/check_your_answers.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-949

#952 Further Welsh changes
  assets/scss/main.scss
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/hearing/support/content.cy.json
  steps/identity/appellant-nino/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/start/benefit-type/BenefitType.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-952

#953 WLA-647: Amend copy on Language Preference question
  steps/start/language-preference/LanguagePreference.js
  steps/start/language-preference/content.cy.json
  steps/start/language-preference/content.en.json
  steps/start/language-preference/template.html
  test/unit/steps/start/LanguagePreference.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-953
