Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-12, with the labels that each got.

#1047 Sscs 8454: SSCS and OCMC test client Webchat webpages are not being updated to reflect Webchat availability.
  assets/js/web-chat.js
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1047

#1046 SSCS-8340 Redis Connection Retry Strategy
  appConfigurations.js
  services/healthcheck.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1046

#1049 SSCS-8434 Opening times copy changes
  commonContent.json
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1049

#1051 updated uc case for pcq
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/page-objects/controls/option.js
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1051

#1052 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1052

#1053 SSCS-8509: Defects in new Webchat integration
  assets/js/web-chat.js
  assets/locale/locale_en-GB.json
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1053

#1055 ran yarn upgrade
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1055

#1057 fixed the functional test
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1057

#1050 Sscs 7682 is save and return flag
  steps/check-your-appeal/CheckYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1050
