Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-10, with the labels that each got.

#993 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-993

#994 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-994

#992 SSCS-7960: Integrate with Antenna webchat prototype
  appConfigurations.js
  assets/js/main.js
  assets/js/web-chat.js
  assets/scss/main.scss
  assets/scss/web-chat.scss
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  views/components/contact-us.html
  views/components/web-chat.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-992

#996 Revert "SSCS-7960: Integrate with Antenna webchat prototype"
  appConfigurations.js
  assets/js/main.js
  assets/js/web-chat.js
  assets/scss/main.scss
  assets/scss/web-chat.scss
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  views/components/contact-us.html
  views/components/web-chat.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-996

#997 Sscs 7960: Integration test of final version of webchat client
  appConfigurations.js
  assets/js/main.js
  assets/js/web-chat.js
  assets/locale/locale_en-GB.json
  assets/scss/main.scss
  assets/scss/web-chat.scss
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  views/components/contact-us.html
  views/components/web-chat.html
  webpack/webpack.common.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-997

#995 SSCS-8328 restart on liveliness failure
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-995

#999 Web-chat false positives
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-999

#1002 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1002

#1003 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1003

#1004 fixed security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1004

#1001 Sscs 7967
  appConfigurations.js
  assets/js/web-chat.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1001

#998 SSCS-7859:SYA - Welsh translation for hearing type screens
  steps/hearing/options/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-998

#1005 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1005

#1006 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1006

#1007 Enable smoke tests for SYA
  config/default.json
  package.json
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/smoke.conf.js
  test/e2e/smoke/appeal.test.js
  test/e2e/smoke/health.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1007

#1000 SSCS-8061 Have MRN copy changes
  README.md
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
  steps/compliance/no-mrn/content.cy.json
  steps/compliance/no-mrn/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1000

#1011 fixed security scan
  Jenkinsfile_nightly
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1011

#1012 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1012

#1013 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1013

#1015 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1015

#1016 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1016
