Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-06, with the labels that each got.

#905 SSCS-7550: Remove Newcastle from allowedRpcs
  Jenkinsfile_CNP
  config/default.json
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-905

#910 Upgrade babel dependencies
  .gitignore
  package.json
  yarn.lock
Labels: ns:sscs, rel:sscs-tribunals-frontend-pr-910

#927 SYA clean build for "Error: getaddrinfo ENOENT sscs-tribunals-api-pr…
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-927

#912 WLA-442: Add LaunchDarkly
  .dockerignore
  .eslintrc.json
  .gitignore
  README.md
  app.js
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/requirements.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/a11y.json
  config/default.json
  config/development_template.yaml
  config/test.yaml
  core/components/launch-darkly.js
  core/utils/featureToggle.js
  middleware/checkWelshToggle.js
  package.json
  services/setupSecrets.js
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/template.html
  test/.eslintrc.json
  test/unit/core/components/launch-darkly.test.js
  test/unit/core/utils/featureToggle.test.js
  test/unit/steps/start/BenefitType.test.js
  views/layouts/question.html
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-912

#920 SSCS-7421: SYA – Cannot read property of undefined at address selection
  components/postcodeLookup/controller.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-920

#917 WLA-557: Hide WebChat from Welsh
  views/components/contact-us.html
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-917

#928 SSCS-7569: S&R/SYA – Show error to users who don’t have the citizen role
  middleware/draftAppealStoreMiddleware.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-928
