Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2020-09, with the labels that each got.

#975 Fixed security scan issue
  appConfigurations.js
  audit.json
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-975

#976 Reverted Fixed security scan issue
  appConfigurations.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-976

#977 Update e2e test journey in cross browser tests
  test/e2e/crossbrowser/supportedBrowsers.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/hearing/theHearing.js
  test/e2e/page-objects/start/postcode-checker.js
  test/e2e/page-objects/upload-evidence/evidenceProvide.js
  test/e2e/saucelabs.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-977

#978 Updated auditjson
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-978

#981 fixed the dependency check
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-981

#982 Fix sya nightly build
  Jenkinsfile_nightly
  audit.json
  bin/ran-yarn-audit.sh
  bin/run-yarn-audit.sh
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-982

#979 Sscs 8046 sya redis connection fix
  package.json
  test/e2e/crossbrowser/supportedBrowsers.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-979

#983 Upgrade terraform
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-983

#984 ignore proxy warning
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-984

#985 Update audit json files
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-985

#986 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-986

#988 Wait step to finish file upload
  test/e2e/page-objects/upload-evidence/uploadEvidencePage.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-988

#989 fix the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-989

#991 SSCS-8125 Update Accessibility Statement for English and Welsh
  README.md
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/content.en.json
  steps/policy-pages/accessibility/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-991
