Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-07, with the labels that each got.

#1198 Suppress warnings addressed in a ticket
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1198

#1199 suppres more low and informational warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1199

#1201 SSCS-8944 JSA end to end test
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.jsa.cy.test.js
  test/e2e/e2e-sya/e2e.jsa.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1201

#1182 added feature flag for cookie banner
  assets/js/check-cookies.js
  assets/js/main.js
  config/custom-environment-variables.json
  config/default.json
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1182

#1200 SSCS - 9061 - allow Social Fund in SYA
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.socialFund.cy.test.js
  test/e2e/e2e-sya/e2e.socialFund.en.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1200

#1203 SSCS-8800 - Allow Income Support Submissions Online
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.incomeSupport.cy.test.js
  test/e2e/e2e-sya/e2e.incomeSupport.en.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1203

#1208 SSCS-9208 Add benefits bereavementSupportPaymentScheme, industrialDeathBenefit, pensionCredits & retirementPension
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/benefit-type/types.js
  test/e2e/page/start/benefitType.cy.test.js
  test/e2e/page/start/benefitType.en.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1208

#1210 SSCS-9216 Other benefits e2e tests
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.bereavementSupportPaymentScheme.cy.test.js
  test/e2e/e2e-sya/e2e.bereavementSupportPaymentScheme.en.test.js
  test/e2e/e2e-sya/e2e.industrialDeathBenefit.cy.test.js
  test/e2e/e2e-sya/e2e.industrialDeathBenefit.en.test.js
  test/e2e/e2e-sya/e2e.pensionCredits.cy.test.js
  test/e2e/e2e-sya/e2e.pensionCredits.en.test.js
  test/e2e/e2e-sya/e2e.retirementPension.cy.test.js
  test/e2e/e2e-sya/e2e.retirementPension.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1210

#1207 SSCS-9358-Added RFE to UC cases under a feature flag
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/compliance/mrn-date/MRNDate.js
  test/e2e/data.en.json
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeESA.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1207

#1215 SSCS-9446 - Fixing Other Benefit type e2e tests
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e-benefit.js
  test/e2e/e2e-sya/e2e.attendanceAllowance.cy.test.js
  test/e2e/e2e-sya/e2e.attendanceAllowance.en.test.js
  test/e2e/e2e-sya/e2e.bereavementBenefit.cy.test.js
  test/e2e/e2e-sya/e2e.bereavementBenefit.en.test.js
  test/e2e/e2e-sya/e2e.ca.cy.test.js
  test/e2e/e2e-sya/e2e.ca.en.test.js
  test/e2e/e2e-sya/e2e.dla.cy.test.js
  test/e2e/e2e-sya/e2e.dla.en.test.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.iidb.cy.test.js
  test/e2e/e2e-sya/e2e.iidb.en.test.js
  test/e2e/e2e-sya/e2e.incomeSupport.cy.test.js
  test/e2e/e2e-sya/e2e.incomeSupport.en.test.js
  test/e2e/e2e-sya/e2e.jsa.cy.test.js
  test/e2e/e2e-sya/e2e.jsa.en.test.js
  test/e2e/e2e-sya/e2e.maternityAllowance.cy.test.js
  test/e2e/e2e-sya/e2e.maternityAllowance.en.test.js
  test/e2e/e2e-sya/e2e.socialFund.cy.test.js
  test/e2e/e2e-sya/e2e.socialFund.en.test.js
  test/e2e/journeys/citizenArchiveCase.en.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1215

#1212 SSCS-9364:SYA - add [User=Chat] attribute to antenna web chat client
  views/components/web-chat.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1212

#1217 Sscs 9422
  .nycrc
  middleware/draftAppealStoreMiddleware.js
  package.json
  test/unit/steps/archive-appeal/ArchiveAppeal.test.js
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1217
