Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-11, with the labels that each got.

#1246 Sscs 9620 sya multipleitem data fix
  middleware/draftAppealStoreMiddleware.js
  steps/appointee/appointee-contact-details/AppointeeContactDetails.js
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-nino/AppellantNINO.js
  steps/representative/representative-details/RepresentativeDetails.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1246

#1259 SSCS-9739: Vaccine Damage (SSCS 7) - Update: SYA Journey
  steps/appeal-form-download/AppealFormDownload.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/benefit-type/types.js
  urls.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1259

#1261 suppress npm audit warnings
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1261

#1262 Upgrade json schema version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1262

#1260 SSCS-9683:Welsh cookie content
  steps/policy-pages/cookie-policy/content.cy.json
  steps/policy-pages/cookie-policy/content.en.json
  steps/policy-pages/cookie-policy/new-cookie-policy.html
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1260
