Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-03, with the labels that each got.

#1097 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1097

#1098 Add welsh tests in cross browser test suite
  package.json
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/saucelabs.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1098

#1094 SSCS-8610 Retry requests
  middleware/draftAppealStoreMiddleware.js
  package.json
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
  test/unit/utils/postcodeChecker.test.js
  utils/postcodeChecker.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1094

#1102 SSCS-8756 - Independence and SSCS-8759 - MRN page
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  test/unit/steps/compliance/check-mrn/CheckMRN.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1102

#1101 SSCS-8749 Fix Title Handling
  steps/identity/appellant-name/AppellantName.js
  test/unit/steps/identity/appellant-name/AppellantName.test.js
  utils/titlesList.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1101

#1100 SSCS-8754 : Allow DLA submissions
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/start/benefit-type/BenefitType.js
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/check-mrn/CheckMRN.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/steps/start/LanguagePreference.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1100

#1108 fix dc failures on SYA
  audit.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1108

#1103 SSCS-8795 Update GTM
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1103

#1109 SSCS-8761:DLA (SYA)- Update: Your reason for appealing page
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/template.html
  test/unit/steps/reasons-for-appealing/ReasonForAppealing.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1109

#1104 Sscs 8662 sya allow rtf
  steps/reasons-for-appealing/evidence-upload/fileTypeWhitelist.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1104

#1110 added dla content for have-contacted-dwp page
  steps/compliance/have-contacted-dwp/HaveContactedDWP.js
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
  steps/compliance/have-contacted-dwp/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1110

#1111 SSCS-8223 - SYA – Duplicate case page (Welsh version)
  steps/errors/duplicate-error/DuplicateError.html
  steps/errors/duplicate-error/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1111

#1113 SSCS-8792 Carers Allowance Steps Handling
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/contact-dwp/ContactDWP.js
  steps/compliance/contact-dwp/template.html
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/have-a-mrn/template.html
  steps/compliance/have-contacted-dwp/HaveContactedDWP.js
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
  steps/compliance/have-contacted-dwp/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/contact-dwp/ContactDWP.test.js
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
  test/unit/steps/compliance/have-contacted-dwp/HaveContactedDWP.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/reasons-for-appealing/ReasonForAppealing.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1113

#1112 SSCS-6475 - SYA - Tell user not to post in MRN
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-provide/content.en.json
  steps/reasons-for-appealing/evidence-provide/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1112

#1114 SSCS-8888: DLA (SYA) - End to End Automated Tests
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.dla.cy.test.js
  test/e2e/e2e-sya/e2e.dla.en.test.js
  test/e2e/page-objects/compliance/dwpIssuingOffice.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1114
