Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-06, with the labels that each got.

#1176 upgrade dependency package version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1176

#1169 SSCS-8936: IIDB (SYA) - End to End Automated Tests
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.iidb.cy.test.js
  test/e2e/e2e-sya/e2e.iidb.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1169

#1172 SSCS-8817 - JSA
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/LanguagePreference.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1172

#1180 Fix dependency failures on SYA
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1180

#1175 SSCS-9162: Invalid benefit type handled for Welsh page
  steps/start/benefit-type/BenefitType.js
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/LanguagePreference.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1175

#1181 Fix dependency failures
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1181

#1177 update error logs
  test/accessibility/a11y.js
  test/accessibility/testApp.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1177

#1179 SSCS-8947 Maternity Allowance feature
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1179

#1183 suppress warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1183

#1185 upgrade postcss dependency version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1185

#1187 SSCS-9127 - Remove redirect urls from IDAM AAT
  Jenkinsfile_CNP
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1187

#1194 SSCS-9267 Update iidb panel text
  steps/start/independence/content.en.json
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1194

#1193 SSCS-9086 - SYA - Error message for docmosis down (Welsh)
  steps/reasons-for-appealing/evidence-upload/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1193

#1190 SSCS-8981 - SYA - Tell user not to post in MRN (Welsh version)
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-upload/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1190

#1192 SSCS-8965 - Mrn date and Try again button on welsh duplicate error page
  steps/errors/duplicate-error/DuplicateError.html
  steps/errors/duplicate-error/DuplicateError.js
  steps/errors/duplicate-error/content.cy.json
  steps/errors/duplicate-error/content.en.json
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-upload/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1192

#1189 sscs 9105 show hearing options on CYA
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
  steps/check-your-appeal/CheckYourAppeal.js
  steps/check-your-appeal/content.cy.json
  steps/check-your-appeal/content.en.json
  steps/check-your-appeal/sections.js
  steps/hearing/options/HearingOptions.js
  steps/hearing/options/answer.html
  steps/hearing/options/content.cy.json
  steps/hearing/options/content.en.json
  steps/hearing/options/cyaHearingOptionsUtils.js
  test/unit/steps/hearing/options/HearingOptions.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1189

#1196 29062021 fix sec scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1196

#1197 Ticket raised to fix Cookie warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1197
