Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-09, with the labels that each got.

#1240 SSCS-9587 - Amend “Recovery from estates” to include 'Deceased'
  package.json
  steps/compliance/dwp-issuing-office-other/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  test/e2e/data.en.json
  test/unit/steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.test.js
  test/unit/steps/compliance/dwp-issuing-office-dla/DWPIssuingOfficeDLA.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.test.js
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1240

#1234 SSCS-9276:Enable mutation test for nightly build
  Jenkinsfile_nightly
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1234

#1235 SSCS-9348 - Keep environment specific branches in sync with master
  Jenkinsfile_CNP
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1235

#1241 SSCS-9602: SYA – Remove draftAppealStoreMiddleware request error log
  middleware/draftAppealStoreMiddleware.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1241

#1243 WIP - Fixing XB tests
  config/default.json
  test/e2e/saucelabs.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1243
