Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-05, with the labels that each got.

#1141 Add dependency version in resolution
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1141

#1143 Fixed smoke test issue
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1143

#1145 Fixed yarn audit issue
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1145

#1148 SSCS-9153: Fix SYA DC failures
  package.json
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1148

#1138 SSCS-9137 Remove non generic evidence to support appeal content
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-provide/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1138

#1137 added welsh translations to Independence page and added four generic …
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
  test/unit/steps/start/Independence.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1137

#1136 Reduce thread count to four
  test/e2e/codecept.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1136

#1156 SSCS-9153: Fix SYA DC failures
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1156

#1135 SSCS-9109 - run in parallel
  package.json
  test/e2e/codecept.conf.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/citizenSignIn.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/page/check-your-appeal/checkYourAppeal.cy.test.js
  test/e2e/page/check-your-appeal/checkYourAppeal.en.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1135

#1155 SSCS-8780 Bereavement benefit feature
  config/custom-environment-variables.json
  config/default.json
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1155

#1160 SSCS-9109 - larger retry for path to live build
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/citizenSignIn.cy.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/page/check-your-appeal/checkYourAppeal.cy.test.js
  test/e2e/page/check-your-appeal/checkYourAppeal.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1160

#1161 SSCS-9109 - Run 4 chunks for path to live
  Jenkinsfile_CNP
  test/e2e/codecept.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1161

#1162 SSCS-9109 run4 chunks for path to live 2
  Jenkinsfile_CNP
  test/e2e/codecept.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1162

#1163 Suppress warnings as ticket raised to fix this
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1163

#1139 Sscs 9108 unify mrn code
  paths.js
  steps.js
  steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office-esa/content.cy.json
  steps/compliance/dwp-issuing-office-esa/content.en.json
  steps/compliance/dwp-issuing-office-esa/template.html
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/content.cy.json
  steps/compliance/dwp-issuing-office/content.en.json
  steps/compliance/dwp-issuing-office/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeESA.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1139

#1166 SSCS-9195: Generic benefit pattern (SYA) - /dwp-issuing-office page -…
  steps.js
  steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.js
  steps/compliance/dwp-issuing-office-attendance-allowance/content.cy.json
  steps/compliance/dwp-issuing-office-attendance-allowance/content.en.json
  steps/compliance/dwp-issuing-office-attendance-allowance/template.html
  steps/compliance/dwp-issuing-office-dla/DWPIssuingOfficeDla.js
  steps/compliance/dwp-issuing-office-dla/content.cy.json
  steps/compliance/dwp-issuing-office-dla/content.en.json
  steps/compliance/dwp-issuing-office-dla/template.html
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.test.js
  test/unit/steps/compliance/dwp-issuing-office-dla/DWPIssuingOfficeDLA.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1166

#1167 Upgrade wdio version and add safari support for SYA XB test suite
  package.json
  test/e2e/crossbrowser/supportedBrowsers.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/helpers/SauceLabsReportingHelper.js
  test/e2e/page-objects/compliance/dwpIssuingOffice.js
  test/e2e/page-objects/sms-notify/smsConfirmation.js
  test/e2e/page-objects/upload-evidence/uploadEvidencePage.js
  test/e2e/saucelabs.conf.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1167

#1168 SSCS-8909: Bereavement Benefit (SYA)- End to End Automated Tests
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.bereavementBenefit.cy.test.js
  test/e2e/e2e-sya/e2e.bereavementBenefit.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1168

#1131 SSCS-9114: Update to equality token algorithm
  steps/pcq/Pcq.js
  steps/pcq/createToken.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1131

#1173 Migrate archive tests to a new file
  test/e2e/codecept.conf.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/journeys/citizenArchiveCase.en.test.js
  test/e2e/journeys/citizenSignIn.en.test.js
  test/e2e/page-objects/compliance/dwpIssuingOffice.js
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1173

#1164 SSCS-8814:IIDB (SYA)- Update: "Check your answers" page
  config/custom-environment-variables.json
  config/default.json
  paths.js
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/dwp-issuing-office/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/dwp-issuing-office-iidb/DWPIssuingOfficeIIDB.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/LanguagePreference.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1164
