Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-02, with the labels that each got.

#1061 SSCS 8150 - Multiple Drafts
  appConfigurations.js
  config/custom-environment-variables.json
  config/default.json
  middleware/draftAppealStoreMiddleware.js
  paths.js
  steps.js
  steps/archive-appeal/ArchiveAppeal.js
  steps/check-your-appeal/CheckYourAppeal.js
  steps/draft-appeals/DraftAppeals.js
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/draft-appeals/template.html
  steps/edit-appeal/EditAppeal.js
  steps/idam/authenticated/Authenticated.js
  steps/new-appeal/NewAppeal.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/archive-appeal/ArchiveAppeal.test.js
  test/unit/steps/draft-appeals/DraftAppeals.test.js
  test/unit/steps/edit-appeal/EditAppeal.test.js
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/idam/Authenticated.test.js
  test/unit/steps/idam/IdamRedirect.test.js
  test/unit/steps/new-appeal/NewAppeal.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1061

#1071 Changed opening times in contact us for help drop down
  commonContent.json
  views/components/contact-us.html
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1071

#1074 PCQ-741: Update to add welsh language.
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  steps/pcq/Pcq.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/controls/option.js
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1074

#1075 Fix pcq functional test
  charts/sscs-tribunals-frontend/values.aat.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1075

#1073 Sscs 8575 media files content
  appConfigurations.js
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  steps/reasons-for-appealing/evidence-upload/content.cy.json
  steps/reasons-for-appealing/evidence-upload/content.en.json
  steps/reasons-for-appealing/evidence-upload/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1073

#1081 SYA Multi-draft UI journey tests
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  test/e2e/codecept.conf.js
  test/e2e/data.en.json
  test/e2e/journeys/citizenSignIn.en.test.js
  test/e2e/page-objects/compliance/dwpIssuingOffice.js
  test/e2e/page-objects/compliance/haveAMRN.js
  test/e2e/page-objects/compliance/mrnDate.js
  test/e2e/page-objects/controls/option.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/draft-appeals/create-new-application.js
  test/e2e/page-objects/draft-appeals/draft-appeals-page.js
  test/e2e/page-objects/hearing/notAttendingHearing.js
  test/e2e/page-objects/hearing/theHearing.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/e2e/page-objects/identity/appointee.js
  test/e2e/page-objects/reasons-for-appealing/reasonForAppealingOnePageForm.js
  test/e2e/page-objects/reasons-for-appealing/reasonsForAppealing.js
  test/e2e/page-objects/sign-in/sign-in-with-valid-creds.js
  test/e2e/page-objects/sign-out/sign-out.js
  test/e2e/page-objects/start/benefit-type.js
  test/e2e/page-objects/start/language-preference.js
  test/e2e/page-objects/start/postcode-checker.js
  test/e2e/page-objects/upload-evidence/evidenceProvide.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1081

#1082 Enable multi-draft on AAT environments
  charts/sscs-tribunals-frontend/values.aat.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1082

#1083 SSCS-8964 upgrade helm
  charts/sscs-tribunals-frontend/Chart.yaml
  test/e2e/codecept.conf.js
  test/e2e/page-objects/compliance/haveAMRN.js
  test/e2e/page-objects/identity/appointee.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1083

#1084 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1084

#1085 fixed security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1085

#1087 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1087

#1088 removed extra comma
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1088

#1089 fixed the dependency check
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1089

#1091 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1091

#1092 reverted version as failing cbt
  audit.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1092

#1093 fixed the failed build
  audit.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1093

#1095 reverted lib as CBT test failing
  audit.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1095

#1096 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1096
