Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-04, with the labels that each got.

#1118 Increase test time limit for functional tests
  Jenkinsfile_nightly
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1118

#1123 sscs 9028 dla tribunal members
  steps/start/independence/content.cy.json
  test/unit/steps/start/Independence.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1123

#1120 SSCS-8609:Multi draft page displayed as entry page for user stored session
  steps/entry/Entry.js
  test/unit/steps/entry/Entry.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1120

#1115 SSCS-7602-Handle exception for evidence upload
  assets/js/evidence-upload/evidence-upload.js
  steps/reasons-for-appealing/evidence-upload/EvidenceUpload.js
  steps/reasons-for-appealing/evidence-upload/content.en.json
  test/unit/middleware/EvidenceUpload.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1115

#1124 SSCS-9034 - Tribunals – Migrate OS places and names API
  components/postcodeLookup/controller.js
  config/default.json
  package.json
  test/unit/components/postcodeLookup/controller.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1124

#1122 SSCS-8982:Status 204 for multiple draft handled
  middleware/draftAppealStoreMiddleware.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1122

#1127 SSCS-8766 Enable attendance allowance benefit type
  config/custom-environment-variables.json
  config/default.json
  paths.js
  steps.js
  steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.js
  steps/compliance/dwp-issuing-office-attendance-allowance/content.cy.json
  steps/compliance/dwp-issuing-office-attendance-allowance/content.en.json
  steps/compliance/dwp-issuing-office-attendance-allowance/template.html
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
  steps/compliance/have-contacted-dwp/template.html
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  steps/draft-appeals/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  steps/start/language-preference/LanguagePreference.js
  test/unit/steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1127

#1129 Increase thread count to shorten test execution time
  test/e2e/codecept.conf.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1129

#1133 SSCS-9107 Make content on have you got MRN page generic
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/have-a-mrn/template.html
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1133

#1132 SSCS-9111 Refator DWP contact page to make generic
  steps/compliance/have-contacted-dwp/content.cy.json
  steps/compliance/have-contacted-dwp/content.en.json
  steps/compliance/have-contacted-dwp/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1132

#1134 SSCS-9113 - Remove FT_ALLOW_UC_HEARING_OPTIONS flag
  appConfigurations.js
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.aat.template.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  steps/hearing/the-hearing/TheHearing.js
  test/unit/steps/hearing/options/HearingOptions.test.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1134
