Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-01, with the labels that each got.

#1058 SSCS-8540 - Tests to verify confirmation page after appeal submission
  steps/check-your-appeal/content.cy.json
  steps/check-your-appeal/content.en.json
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/page-objects/cya/appealSubmitConfirmation.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/cya/submitAppeal.js
  utils/DateUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1058

#1059 Upgrade axios version in lock file
  package.json
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1059

#1060 fixed the security scan issue
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1060

#1062 fixed security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1062

#1063 fixed the functional test for preview env
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  test/e2e/page-objects/cya/checkYourAppeal.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1063

#1064 enabled welsh for aat env
  charts/sscs-tribunals-frontend/values.aat.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1064

#1065 Adding env variables in zap security script
  security.sh
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/page-objects/cya/appealSubmitConfirmation.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1065

#1067 Update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1067

#1068 ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1068

#1069 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1069

#1056 PCQ: Add language preference to PCQ invoking parameters
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  steps/pcq/Pcq.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/controls/option.js
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1056

#1072 Revert "PCQ: Add language preference to PCQ invoking parameters"
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  steps/pcq/Pcq.js
  test/e2e/e2e-sya/e2e.cy.test.js
  test/e2e/e2e-sya/e2e.en.cbtest.js
  test/e2e/e2e-sya/e2e.en.test.js
  test/e2e/e2e-sya/e2e.esa.cy.test.js
  test/e2e/e2e-sya/e2e.esa.en.test.js
  test/e2e/e2e-sya/e2e.uc.cy.test.js
  test/e2e/e2e-sya/e2e.uc.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  test/e2e/journeys/hearingOptionsWithManualPostcodeLookup.en.test.js
  test/e2e/journeys/manualPostcodeLookup.cy.test.js
  test/e2e/journeys/manualPostcodeLookup.en.test.js
  test/e2e/page-objects/controls/option.js
  test/e2e/page-objects/pcq/pcq.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1072
