Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2021-08, with the labels that each got.

#1174 update cookie banner
  .dockerignore
  .eslintignore
  .gitignore
  .nycrc
  Jenkinsfile_CNP
  appConfigurations.js
  assets/js/check-cookies.js
  assets/js/main.js
  assets/scss/date-picker.scss
  assets/scss/govuk-frontend-3.11.0.min.css
  assets/scss/main.scss
  components/postcodeLookup/assets/govuk-frontend-3.11.0.min.css
  components/postcodeLookup/assets/main.js
  gulpfile.js
  package.json
  paths.js
  steps.js
  steps/policy-pages/cookie-policy/Cookies.js
  steps/policy-pages/cookie-policy/cookie-success-banner.njk
  steps/policy-pages/cookie-policy/new-cookie-policy.html
  steps/policy-pages/cookie-policy/old-cookie-policy.html
  steps/policy-pages/cookie-policy/template.html
  test/accessibility/a11y.js
  test/unit/steps/policy-pages/Cookies.test.js
  views/components/cookie-banner.html
  views/components/errors.njk
  views/components/globals.html
  views/components/header.njk
  views/components/navigation.html
  views/layouts/two_thirds.html
  webpack/webpack.common.js
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1174

#1219 Update README.md
  README.md
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1219

#1223 Upgrade tar version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1223

#1209 SSCS-9381: Enable fortify scan
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1209

#1222 SSCS-9480: Unable to Archive "Other Benefit" cases on multi-draft page
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1222

#1205 Cookie banner UI tests
  test/e2e/page/cookieBanner/cookie-content.json
  test/e2e/page/cookieBanner/cookieBanner.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1205

#1216 sscs 9368 user gets a warning when archiving
  assets/js/archive-warning.js
  assets/js/main.js
  assets/scss/main.scss
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/draft-appeals/template.html
  test/e2e/page-objects/draft-appeals/draft-appeals-page.js
  views/components/archive-warning.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1216

#1224 Sscs 9485
  audit.json
  test/e2e/crossbrowser/supportedBrowsers.js
  test/e2e/e2e-sya/e2e-benefit.js
  test/e2e/e2e-sya/e2e.incomeSupport.cy.test.js
  test/e2e/e2e-sya/e2e.incomeSupport.en.test.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/upload-evidence/uploadEvidencePage.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1224

#1225 ignore known low warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1225

#1230 Include low security warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1230

#1233 Sscs 9464 2
  charts/sscs-tribunals-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1233

#1228 update nodejs in chart
  charts/sscs-tribunals-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1228

#1231 Sscs 9477 2
  paths.js
  steps.js
  steps/compliance/dwp-issuing-office-other/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office-other/content.cy.json
  steps/compliance/dwp-issuing-office-other/content.en.json
  steps/compliance/dwp-issuing-office-other/template.html
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.test.js
  test/unit/steps/compliance/dwp-issuing-office-dla/DWPIssuingOfficeDLA.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeESA.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.test.js
  test/unit/steps/compliance/dwp-issuing-office-iidb/DWPIssuingOfficeIIDB.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1231

#1226 Sscs 9477 dwp office broken
  paths.js
  steps.js
  steps/compliance/dwp-issuing-office-other/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office-other/content.cy.json
  steps/compliance/dwp-issuing-office-other/content.en.json
  steps/compliance/dwp-issuing-office-other/template.html
  steps/compliance/dwp-issuing-office/DWPIssuingOffice.js
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/dwp-issuing-office-attendance-allowance/DWPIssuingOfficeAttendanceAllowance.test.js
  test/unit/steps/compliance/dwp-issuing-office-dla/DWPIssuingOfficeDLA.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeESA.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.test.js
  test/unit/steps/compliance/dwp-issuing-office-iidb/DWPIssuingOfficeIIDB.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1226

#1229 SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/benefit-type/types.js
  test/e2e/data.en.json
  test/unit/utils/stringUtils.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1229

#1232 SSCS-9502: Change Benefit name from Pension Credits to Pension Credit
  steps/compliance/dwp-issuing-office-other/DWPIssuingOfficeEsa.js
  steps/compliance/dwp-issuing-office/template.html
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/benefit-type/types.js
  test/e2e/data.en.json
  test/e2e/e2e-sya/e2e.pensionCredits.cy.test.js
  test/e2e/e2e-sya/e2e.pensionCredits.en.test.js
  test/e2e/page/start/benefitType.cy.test.js
  test/e2e/page/start/benefitType.en.test.js
  test/unit/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.test.js
  test/unit/steps/compliance/dwp-issuing-office/DWPIssuingOffice.test.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/utils/stringUtils.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1232
