Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2022-03, with the labels that each got.

#1295 update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1295

#1297 suppress warnings
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1297

#1298 update suppression file
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1298

#1296 SSCS-10236 updating helm chart version
  charts/sscs-tribunals-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1296

#1302 Update known issues
  test/accessibility/a11y.js
  test/e2e/journeys/datesCantAttend.cy.test.js
  test/e2e/journeys/datesCantAttend.en.test.js
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1302

#1305 SSCS-10306: fix minimist dependency
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1305

#1307 Create CODEOWNERS
  CODEOWNERS
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1307
