Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2022-02, with the labels that each got.

#1283 Sscs 9025 automation tests
  .eslintrc.json
  Jenkinsfile_nightly
  test/.eslintrc.json
  test/e2e/codecept.conf.js
  test/e2e/journeys/draftSubmitVerify.cy.test.js
  test/e2e/journeys/draftSubmitVerify.en.test.js
  test/e2e/page-objects/compliance/haveContactedDWP.js
  test/e2e/page-objects/compliance/noMRN.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/draft-appeals/draft-appeals-page.js
  test/e2e/page-objects/identity/appellantDetails.js
  test/e2e/page-objects/sign-in/sign-in-with-valid-creds.js
  test/e2e/page-objects/tribunals-case-api/getCaseData.js
  test/unit/getCaseData.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1283

#1284 Sscs 10121 - Upgrade dependencies
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1284

#1287 upgrade helm chart
  charts/sscs-tribunals-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1287

#1290 upgrade dependency version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1290

#1270 Remove retries from frontend
  middleware/draftAppealStoreMiddleware.js
  steps/check-your-appeal/CheckYourAppeal.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/check-your-appeal/CheckYourAppeal.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1270

#1291 Reset yarn suppression file
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1291

#1293 fix npm dependency failure
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1293
