Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2022-04, with the labels that each got.

#1312 SSCS-10368 Updating Node
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1312

#1313 SSCS-10368 suppressing dependencies
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1313

#1300 SSCS-10213: update web chat config
  assets/locale/locale_en-GB.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1300

#1315 SSCS-10376: Suppressing Dependencies
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1315

#1317 add page refresh
  test/e2e/page/cookieBanner/cookieBanner.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1317

#1316 SSCS-10429-Welsh-Accessibility-Statement
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/template.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1316

#1319 Fixing Nightly Build - Updating audit.json
  audit.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1319
