Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2022-05, with the labels that each got.

#1322 Add now to contact centre closed
  assets/locale/locale_en-GB.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1322

#1323 Fix build 25042022
  Jenkinsfile_nightly
  test/e2e/page/cookieBanner/cookieBanner.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1323

#1324 Add retries to tag checks
  test/e2e/page/cookieBanner/cookieBanner.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1324

#1320 SSCS-10486: Update SYA contact opening hours
  commonContent.json
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1320
