Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2022-01, with the labels that each got.

#1266 Update “Save” button on Welsh cookie policy page
  steps/policy-pages/cookie-policy/content.cy.json
  steps/policy-pages/cookie-policy/content.en.json
  steps/policy-pages/cookie-policy/new-cookie-policy.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1266

#1269 SSCS-9941 Upgrade one-per-page to new version with pings.
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1269

#1273 SSCS-9941 Suppress postcss audit.
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1273

#1267 Fix all changes for SSCS-9828
  steps/appeal-form-download/AppealFormDownload.js
  steps/appeal-form-download/content.en.json
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/template.html
  steps/start/benefit-type/types.js
  test/e2e/page/start/benefitType.cy.test.js
  test/e2e/page/start/benefitType.en.test.js
  test/unit/steps/identity/appeal-form-download/AppealFormDownload.test.js
  test/unit/utils/stringUtils.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1267

#1274 suppress warning
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1274

#1276 upgrade npm package
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1276

#1277 SSCS-9991-Update-Accesiblity: Accesibility page updated
  steps/policy-pages/accessibility/content.en.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1277

#1279 Upgrade dependency package
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1279
