Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2023-08, with the labels that each got.

#1395 CVEFix - 07.08.23
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1395

#1396 Security Fix - 08.08.23
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1396

#1398 add sscs settings for xui
  config/default.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1398

#1399 Security Fix - 10.08.23
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1399

#1402 Fix yarn warning
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1402

#1400 SSCSCI-8
  urls.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1400
