Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2023-04, with the labels that each got.

#1367 SSCS-11479 - updated package.json
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sscs-tribunals-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1367

#1368 SSCS-11479 - CVEFix.13.04.23
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1368

#1376 remove security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1376

#1375 upgrade for yarn from v1 to v3
  .dockerignore
  .gitignore
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  package.json
  test/e2e/page-objects/start/independence.js
  test/e2e/smoke/appeal.test.js
  urls.js
  yarn-audit-issues-result
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1375

#1379 Yarn upgrade
  test/e2e/codecept.conf.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1379
