Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-08, with the labels that each got.

#1499 SSCSCI-984: Update Telephone and Webchat Opening Times
  commonContent.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1499

#1491 Add dynatrace snippet - please QA <3
  views/components/globals.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1491

#1502 Update suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1502
