Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-11, with the labels that each got.

#1553 SSCSCI-1212
  components/postcodeLookup/content.en.json
  components/postcodeLookup/contentIba.cy.json
  components/postcodeLookup/contentIba.en.json
  components/postcodeLookup/controller.js
  package.json
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/identity/appellant-contact-details/content.cy.json
  steps/identity/appellant-contact-details/content.en.json
  steps/identity/appellant-international-contact-details/AppellantInternationalContactDetails.js
  steps/identity/appellant-international-contact-details/answer.html
  steps/identity/appellant-international-contact-details/content.cy.json
  steps/identity/appellant-international-contact-details/content.en.json
  steps/identity/appellant-international-contact-details/template.html
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/content.cy.json
  steps/representative/representative-details/content.en.json
  steps/representative/representative-international-details/RepresentativeInternationalDetails.js
  steps/representative/representative-international-details/answer.html
  steps/representative/representative-international-details/content.cy.json
  steps/representative/representative-international-details/content.en.json
  steps/representative/representative-international-details/template.html
  test/unit/steps/identity/appellant-international-contact-details/AppellantInternationalContactDetails.test.js
  test/unit/steps/representative/representative-international-details/RepresentativeInternationalDetails.test.js
  utils/regex.js
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1553

#1557 audit fix
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1557

#1561 suppression
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1561

#1558 Sscsci 1357 irn to review decision change
  paths.js
  steps.js
  steps/check-your-appeal/CheckYourAppeal.js
  steps/check-your-appeal/content.cy.json
  steps/check-your-appeal/content.en.json
  steps/check-your-appeal/template.html
  steps/compliance/check-mrn/content.cy.json
  steps/compliance/check-mrn/content.en.json
  steps/compliance/have-a-mrn/HaveAMRN.js
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.en.json
  steps/compliance/mrn-date/content.cy.json
  steps/compliance/mrn-date/content.en.json
  steps/compliance/mrn-over-month-late/content.cy.json
  steps/compliance/mrn-over-month-late/content.en.json
  steps/compliance/need-rdn/NeedRDN.js
  steps/compliance/need-rdn/content.cy.json
  steps/compliance/need-rdn/content.en.json
  steps/compliance/need-rdn/template.html
  steps/identity/appellant-ibca-reference/content.cy.json
  steps/identity/appellant-ibca-reference/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/create-account/content.cy.json
  steps/start/create-account/content.en.json
  steps/start/create-account/template.html
  test/unit/steps/compliance/have-a-mrn/HaveAMRN.test.js
  test/unit/steps/compliance/need-rdn/NeedRDN.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1558

#1562 SSCSCI-1421
  steps/archive-appeal/ArchiveAppeal.js
  steps/draft-appeals/DraftAppeals.js
  steps/edit-appeal/EditAppeal.js
  steps/pcq/Pcq.js
  test/unit/steps/archive-appeal/ArchiveAppeal.test.js
  test/unit/steps/draft-appeals/DraftAppeals.test.js
  test/unit/steps/edit-appeal/EditAppeal.test.js
  test/unit/steps/pcq/Pcq.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1562

#1568 changing env variable
  appConfigurations.js
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  package.json
  steps/entry/Entry.js
  test/unit/steps/entry/Entry.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1568
