Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-04, with the labels that each got.

#1470 Updated suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1470

#1471 Add CVE-2023-45133 to suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1471

#1472 Add express to resolutions
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1472

#1475 chore: test pr for automation
  README.md
  appConfigurations.js
  assets/js/main.js
  assets/js/web-chat.js
  package.json
  test/e2e/codecept.conf.js
  test/unit/steps/appointee/appointee-name/Appointee-name.test.js
  test/unit/steps/identity/appellant-name/AppellantName.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1475

#1480 SSCSCI-608
  bin/generate-ssl-options.sh
  keys/server.cert
  keys/server.key
  package.json
  server.js
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1480
