Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-12, with the labels that each got.

#1569 Fix nino test data issue for UI tests
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/util/randomData.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1569

#1571 Sscsci 1440: ibca additional changes
  assets/images/rdn-date.png
  assets/scss/h-progress-bar.scss
  commonContent.json
  steps/check-your-appeal/content.cy.json
  steps/check-your-appeal/content.en.json
  steps/compliance/check-mrn/template.html
  steps/compliance/mrn-date/template.html
  steps/confirmation/Confirmation.js
  steps/confirmation/content.cy.json
  steps/confirmation/content.en.json
  steps/confirmation/template.html
  test/unit/steps/confirmation/Confirmation.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1571

#1570 SSCSCI-1437: Implementing ibca reference regex
  steps/identity/appellant-ibca-reference/content.cy.json
  steps/identity/appellant-ibca-reference/content.en.json
  test/unit/utils/regex.test.js
  utils/regex.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1570

#1573 Update vulnerable dependency and suppress
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1573

#1575 Adding suppression to known list
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1575

#1563 SSCSCI-1356 draft appeal fix
  middleware/draftAppealStoreMiddleware.js
  paths.js
  steps.js
  steps/draft-appeals/DraftAppeals.js
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/draft-appeals/template.html
  steps/identity/appellant-dob/AppellantDOB.js
  steps/identity/appellant-in-mainland-uk/AppellantInMainlandUk.js
  steps/identity/appellant-in-mainland-uk/content.cy.json
  steps/identity/appellant-in-mainland-uk/content.en.json
  steps/identity/appellant-in-mainland-uk/template.html
  steps/representative/representative-in-mainland-uk/RepresentativeInMainlandUk.js
  steps/representative/representative-in-mainland-uk/content.cy.json
  steps/representative/representative-in-mainland-uk/content.en.json
  steps/representative/representative-in-mainland-uk/template.html
  steps/representative/representative/Representative.js
  test/unit/steps/draft-appeals/DraftAppeals.test.js
  test/unit/steps/identity/appellant-dob/AppellantDOB.test.js
  test/unit/steps/identity/appellant-in-mainland-uk/AppellantInMainlandUk.test.js
  test/unit/steps/representative/representative-in-mainland-uk/RepresentativeInMainlandUk.test.js
  test/unit/steps/representative/representative/Representative.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1563

#1577 SSCSCI-1470 enum refresh fetch
  server.js
  test/unit/utils/enumJsonLists.test.js
  utils/enumJsonLists.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1577

#1576 SSCSCI-1422 fixing missing rep international postcode bug
  steps/representative/representative-international-details/RepresentativeInternationalDetails.js
  test/unit/steps/representative/representative-international-details/RepresentativeInternationalDetails.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1576

#1580 Resuppression
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1580

#1564 SSCSCI-1393: Importing Welsh translation for IBC
  commonContent.json
  components/postcodeLookup/contentIba.cy.json
  steps/check-your-appeal/content.cy.json
  steps/compliance/check-mrn/content.cy.json
  steps/compliance/have-a-mrn/content.cy.json
  steps/compliance/mrn-date/content.cy.json
  steps/compliance/mrn-over-month-late/content.cy.json
  steps/compliance/need-rdn/content.cy.json
  steps/hearing/options/content.cy.json
  steps/hearing/the-hearing/content.cy.json
  steps/identity/appellant-ibca-reference/content.cy.json
  steps/identity/appellant-in-mainland-uk/content.cy.json
  steps/identity/appellant-international-contact-details/content.cy.json
  steps/identity/appellant-role/content.cy.json
  steps/reasons-for-appealing/evidence-provide/EvidenceProvide.js
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/other-reasons-for-appealing/OtherReasonForAppealing.js
  steps/reasons-for-appealing/other-reasons-for-appealing/content.cy.json
  steps/reasons-for-appealing/other-reasons-for-appealing/content.en.json
  steps/reasons-for-appealing/other-reasons-for-appealing/template.html
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/representative/representative-in-mainland-uk/content.cy.json
  steps/representative/representative-international-details/content.cy.json
  steps/start/benefit-type/content.cy.json
  steps/start/benefit-type/content.en.json
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  test/unit/steps/identity/appellant-in-mainland-uk/AppellantInMainlandUk.test.js
  test/unit/steps/reasons-for-appealing/OtherReasonForAppealing.test.js
  test/unit/steps/representative/representative-in-mainland-uk/RepresentativeInMainlandUk.test.js
  test/unit/steps/start/Independence.test.js
  utils/stringUtils.js
  views/components/contact-us.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1564

#1574 SSCSCI-1463 fixing international text-reminders flow
  steps/sms-notify/send-to-number/SendToNumber.js
  steps/sms-notify/sms-confirmation/SmsConfirmation.js
  steps/sms-notify/text-reminders/TextReminders.js
  test/unit/steps/sms-notify/send-to-number/SendToNumber.test.js
  test/unit/steps/sms-notify/sms-confirmation/SmsConfirmation.test.js
  test/unit/steps/sms-notify/text-reminders/TextReminders.test.js
  test/util/randomData.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1574

#1582 SSCSCI-1388: Nightly builds 2
  test/e2e/page/cookieBanner/cookieBanner.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1582

#1555 Updating jenkinsCNP to output artifacts
  Jenkinsfile_CNP
  test/e2e/page/cookieBanner/cookieBanner.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1555
