Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-07, with the labels that each got.

#1493 Update suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1493

#1494 Sonar exclusions update
  sonar-project.properties
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1494

#1482 SSCSCI-699
  appConfigurations.js
  assets/js/main.js
  assets/js/web-chat-scotland.js
  commonContent.json
  views/components/contact-us.html
  views/components/globals.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1482
