Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-10, with the labels that each got.

#1537 Sscsci 1115 ibca reference
  paths.js
  steps.js
  steps/identity/appellant-dob/AppellantDOB.js
  steps/identity/appellant-ibca-ref/AppellantIBCARef.js
  steps/identity/appellant-ibca-ref/content.cy.json
  steps/identity/appellant-ibca-ref/content.en.json
  steps/identity/appellant-ibca-ref/template.html
  test/unit/steps/identity/appellant-dob/AppellantDOB.test.js
  test/unit/steps/identity/appellant-ibca-ref/appellantIBCARef.test.js
  utils/regex.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1537

#1533 SSCSCI-1114 skipping DWP office page for IBA
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.js
  steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.js
  test/unit/steps/compliance/mrn-date/MRNDate.test.js
  test/unit/steps/compliance/mrn-over-month-late/MRNOverOneMonthLate.test.js
  test/unit/steps/compliance/mrn-over-thirteen-months-late/MRNOverThirteenMonthsLate.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1533

#1539 SSCSCI-1113
  assets/images/irn-date.png
  paths.js
  steps.js
  steps/check-your-appeal/CheckYourAppeal.js
  steps/check-your-appeal/content.en.json
  steps/check-your-appeal/sections.js
  steps/compliance/check-irn/CheckIRN.js
  steps/compliance/check-irn/content.cy.json
  steps/compliance/check-irn/content.en.json
  steps/compliance/check-irn/template.html
  steps/compliance/have-an-irn/HaveAnIRN.js
  steps/compliance/irn-date/IRNDate.js
  steps/compliance/irn-date/content.cy.json
  steps/compliance/irn-date/content.en.json
  steps/compliance/irn-date/irnDateOnImage.js
  steps/compliance/irn-date/template.html
  steps/compliance/irn-over-month-late/IRNOverOneMonthLate.js
  steps/compliance/irn-over-month-late/content.cy.json
  steps/compliance/irn-over-month-late/content.en.json
  steps/compliance/irn-over-month-late/template.html
  steps/compliance/irn-over-thirteen-months-late/IRNOverThirteenMonthsLate.js
  steps/compliance/irn-over-thirteen-months-late/content.cy.json
  steps/compliance/irn-over-thirteen-months-late/content.en.json
  steps/compliance/irn-over-thirteen-months-late/template.html
  test/unit/steps/compliance/have-an-irn/HaveAnIRN.test.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1539

#1535 SSCSCI-1116 use of international addresses for IBA cases
  paths.js
  steps.js
  steps/appointee/appointee-dob/AppointeeDOB.js
  steps/appointee/appointee-in-uk/AppointeeInUk.js
  steps/appointee/appointee-in-uk/content.cy.json
  steps/appointee/appointee-in-uk/content.en.json
  steps/appointee/appointee-in-uk/template.html
  steps/appointee/appointee-international-contact-details/AppointeeInternationalContactDetails.js
  steps/appointee/appointee-international-contact-details/answer.html
  steps/appointee/appointee-international-contact-details/content.cy.json
  steps/appointee/appointee-international-contact-details/content.en.json
  steps/appointee/appointee-international-contact-details/template.html
  steps/appointee/appointee-name/AppointeeName.js
  steps/appointee/same-address/SameAddress.js
  steps/entry/Entry.js
  steps/identity/appellant-ibca-ref/AppellantIBCARef.js
  steps/identity/appellant-in-uk/AppellantInUk.js
  steps/identity/appellant-in-uk/content.cy.json
  steps/identity/appellant-in-uk/content.en.json
  steps/identity/appellant-in-uk/template.html
  steps/identity/appellant-international-contact-details/AppellantInternationalContactDetails.js
  steps/identity/appellant-international-contact-details/answer.html
  steps/identity/appellant-international-contact-details/content.cy.json
  steps/identity/appellant-international-contact-details/content.en.json
  steps/identity/appellant-international-contact-details/template.html
  steps/identity/appellant-name/AppellantName.js
  steps/representative/representative-in-uk/RepresentativeInUk.js
  steps/representative/representative-in-uk/content.cy.json
  steps/representative/representative-in-uk/content.en.json
  steps/representative/representative-in-uk/template.html
  steps/representative/representative-international-details/RepresentativeInternationalDetails.js
  steps/representative/representative-international-details/answer.html
  steps/representative/representative-international-details/content.cy.json
  steps/representative/representative-international-details/content.en.json
  steps/representative/representative-international-details/template.html
  steps/representative/representative/Representative.js
  steps/start/benefit-type/BenefitType.js
  test/unit/steps/appointee/appointee-dob/AppointeeDOB.test.js
  test/unit/steps/appointee/appointee-in-uk/AppointeeInUk.test.js
  test/unit/steps/appointee/appointee-international-contact-details/AppointeeInternationalContactDetails.test.js
  test/unit/steps/appointee/same-address/SameAddress.test.js
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/identity/appellant-ibca-ref/AppellantIBCARef.test.js
  test/unit/steps/identity/appellant-in-uk/AppellantInUk.test.js
  test/unit/steps/identity/appellant-international-contact-details/AppellantInternationalContactDetails.test.js
  test/unit/steps/representative/representative-in-uk/RepresentativeInUk.test.js
  test/unit/steps/representative/representative-international-details/RepresentativeInternationalDetails.test.js
  test/unit/steps/representative/representative/Representative.test.js
  test/unit/steps/start/BenefitType.test.js
  utils/countriesList.json
  utils/portOfEntryList.json
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1535

#1545 Sscsci 1119 wording change
  Jenkinsfile_CNP
  steps/hearing/the-hearing/TheHearing.js
  steps/hearing/the-hearing/content.cy.json
  steps/hearing/the-hearing/content.en.json
  steps/identity/appointee/Appointee.js
  steps/identity/appointee/content.cy.json
  steps/identity/appointee/content.en.json
  steps/reasons-for-appealing/other-reasons-for-appealing/OtherReasonForAppealing.js
  steps/reasons-for-appealing/other-reasons-for-appealing/content.cy.json
  steps/reasons-for-appealing/other-reasons-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/content.cy.json
  steps/reasons-for-appealing/reason-for-appealing/content.en.json
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/types.js
  steps/start/independence/Independence.js
  steps/start/independence/content.cy.json
  steps/start/independence/content.en.json
  steps/start/independence/template.html
  test/e2e/page-objects/identity/appointee.js
  test/e2e/smoke.conf.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
  test/unit/steps/identity/appointee/Appointee.test.js
  test/unit/steps/reasons-for-appealing/OtherReasonForAppealing.test.js
  test/unit/steps/start/Independence.test.js
  utils/stringUtils.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1545

#1549 Sscsci 1115 ibca reference screen update
  paths.js
  steps/compliance/have-an-irn/HaveAnIRN.js
  steps/identity/appellant-dob/AppellantDOB.js
  steps/identity/appellant-ibca-ref/AppellantIBCARef.js
  steps/identity/appellant-ibca-ref/content.cy.json
  steps/identity/appellant-ibca-ref/content.en.json
  test/unit/steps/compliance/have-an-irn/HaveAnIRN.test.js
  test/unit/steps/identity/appellant-dob/AppellantDOB.test.js
  test/unit/steps/identity/appellant-ibca-ref/AppellantIBCARef.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1549

#1551 SSCSCI-1107 Update to contact us section
  commonContent.json
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1551

#1552 reinstate safe filter as content contains html
  views/layouts/check_your_answers.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1552

#1554 Sscsci 1119 iba wording change update
  steps/hearing/options/HearingOptions.js
  steps/hearing/options/content.cy.json
  steps/hearing/options/content.en.json
  steps/hearing/options/template.html
  steps/hearing/the-hearing/TheHearing.js
  steps/hearing/the-hearing/content.cy.json
  steps/hearing/the-hearing/content.en.json
  steps/hearing/the-hearing/template.html
  steps/reasons-for-appealing/evidence-provide/EvidenceProvide.js
  steps/reasons-for-appealing/evidence-provide/content.cy.json
  steps/reasons-for-appealing/evidence-provide/content.en.json
  test/unit/steps/hearing/options/HearingOptions.test.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
  test/unit/steps/reasons-for-appealing/EvidenceProvide.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1554
