Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-01, with the labels that each got.

#1432 Revert "SSCSCI-22-2 - Advanced Security Features Not Enabled "
  appConfigurations.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1432

#1429 Latest: SSCS-10112 - Judicial- CCD- Non-standard captialised names are format…
  steps/appointee/appointee-name/AppointeeName.js
  steps/identity/appellant-name/AppellantName.js
  steps/representative/representative-details/RepresentativeDetails.js
  test/unit/steps/appointee/appointee-name/Appointee-name.test.js
  test/unit/steps/identity/appellant-name/AppellantName.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1429

#1436 Fixing pipeline issues
  Jenkinsfile_nightly
  bin/run-yarn-audit.sh
  package.json
  test/e2e/crossbrowser/supportedBrowsers.js
  yarn-audit-issues-result
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1436
