Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-09, with the labels that each got.

#1507 Danny - Fix CSP
  appConfigurations.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1507

#1509 Suppression update
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1509

#1500 SSCSCI-897 webpack bump
  .dockerignore
  Dockerfile
  README.md
  package.json
  server.js
  sonar-project.properties
  test/webpack.config.js
  webpack.config.js
  webpack/app.js
  webpack/govukFrontend.js
  webpack/scss.js
  webpack/webpack.common.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1500

#1515 Pre-IBA work - CVE removal
  assets/js/main.js
  assets/js/web-chat-scotland.js
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1515

#1516 Delete iisnode.yml
  iisnode.yml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1516

#1517 IBA prep - Upgrade to Yarn v4
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.5.1.cjs
  .yarn/releases/yarn-4.4.1.cjs
  .yarnrc.yml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1517

#1519 remove yarn version from yarnrc
  .yarnrc.yml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1519

#1521 local env fixes
  .gitignore
  bin/pull_postcode_token.sh
  config/default.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1521

#1520 Add yarn start:dev command to remove need for docker compose (hopefully)
  README.md
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1520

#1525 SSCSCI-1039
  charts/sscs-tribunals-frontend/values.preview.template.yaml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1525

#1526 spiking iba
  .eslintrc.json
  Jenkinsfile_CNP
  appConfigurations.js
  steps/draft-appeals/DraftAppeals.js
  steps/entry/Entry.js
  steps/new-appeal/NewAppeal.js
  steps/start/benefit-type/BenefitType.js
  steps/start/benefit-type/content.en.json
  steps/start/benefit-type/types.js
  steps/start/create-account/CreateAccount.js
  steps/start/create-account/content.cy.json
  steps/start/create-account/content.en.json
  steps/start/create-account/template.html
  steps/start/independence/Independence.js
  steps/start/independence/content.en.json
  steps/start/language-preference/LanguagePreference.js
  steps/start/postcode-checker/PostcodeChecker.js
  test/e2e/page-objects/start/benefit-type.js
  test/unit/steps/draft-appeals/DraftAppeals.test.js
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/new-appeal/NewAppeal.test.js
  test/unit/steps/start/BenefitType.test.js
  test/unit/steps/start/CreateAccount.test.js
  test/unit/steps/start/Independence.test.js
  test/unit/steps/start/LanguagePreference.test.js
  test/unit/steps/start/PostcodeChecker.test.js
  test/unit/utils/benefitTypeUtils.test.js
  utils/benefitTypeUtils.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1526

#1534 replacing forceIba query with env variable check
  README.md
  appConfigurations.js
  package.json
  steps/draft-appeals/DraftAppeals.js
  test/unit/steps/entry/Entry.test.js
  test/unit/utils/benefitTypeUtils.test.js
  utils/benefitTypeUtils.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1534
