Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-03, with the labels that each got.

#1455 SSCSCI-767: Remove Jquery and Cookie Toggles
  appConfigurations.js
  config/custom-environment-variables.json
  config/default.json
  views/components/globals.html
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1455

#1469 Updated suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1469

#1449 Sscs 12389 update interpreter
  steps/hearing/arrangements/languages.js
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1449
