Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2024-06, with the labels that each got.

#1489 Suppression for CVE-2024-29415
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1489

#1487 Sscsci 499 upgrade java node versions
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1487

#1490 Minor and patch upgrades to fix CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1490
