Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2025-01, with the labels that each got.

#1585 minor bug fix
  steps/representative/representative-in-mainland-uk/RepresentativeInMainlandUk.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1585

#1587 SSCSCI-1478: IBA google tag manager
  appConfigurations.js
  views/components/globals.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1587

#1590 Fix: updating sonarcloud exclusions
  sonar-project.properties
Labels: ns:sscs, prd:sscs

#1592 Sscsci 1529: update accessibility statement for ibca
  steps/policy-pages/accessibility/Accessibility.js
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/content.en.json
  steps/policy-pages/accessibility/template.html
  test/unit/steps/policy-pages/Accessibility.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm

#1588 Remove vendors~main.css references
  audit.json
  views/components/globals.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1588

#1596 SSCSCI-1529-v2: new updates to the accessibility page
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/content.en.json
  steps/policy-pages/accessibility/template.html
Labels: ns:sscs, prd:sscs, enable_keep_helm

#1593 SSCSCI-1451: updating rdn date graphic
  assets/images/rdn-date.png
  steps/compliance/mrn-date/MRNDate.js
  steps/compliance/mrn-date/mrnDateOnImage.js
  test/unit/utils/DateUtils.test.js
  utils/DateUtils.js
Labels: ns:sscs, prd:sscs, enable_keep_helm

#1600 Sscsci 1603: iba accessibility welsh translation
  steps/policy-pages/accessibility/content.cy.json
  steps/policy-pages/accessibility/content.en.json
  views/components/contact-us.html
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, enable_keep_helm

#1586 SSCSCI-1502: Fix for the answers to also have Welsh option available
  steps/identity/appellant-contact-details/AppellantContactDetails.js
  steps/reasons-for-appealing/other-reasons-for-appealing/OtherReasonForAppealing.js
  steps/representative/representative-details/RepresentativeDetails.js
  utils/answer.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1586

#1583 SSCSCI-1501 existing welsh confirmation overlap bug CI fix
  assets/scss/h-progress-bar.scss
  steps/confirmation/content.cy.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1583

#1595 SSCSCI-1590
  paths.js
  steps.js
  steps/entry/Entry.js
  steps/policy-pages/request-ibc-appeal-form/RequestIbcAppealForm.js
  steps/policy-pages/request-ibc-appeal-form/content.cy.json
  steps/policy-pages/request-ibc-appeal-form/content.en.json
  steps/policy-pages/request-ibc-appeal-form/template.html
  test/unit/steps/entry/Entry.test.js
  test/unit/steps/policy-pages/RequestIbcAppealForm.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm

#1594 SSCSCI-1453
  steps/identity/appellant-ibca-reference/AppellantIBCAReference.js
  steps/identity/appellant-name/AppellantName.js
  steps/identity/appellant-name/template.html
  steps/representative/representative-details/RepresentativeDetails.js
  steps/representative/representative-details/template.html
  steps/representative/representative-international-details/RepresentativeInternationalDetails.js
  steps/representative/representative-international-details/content.cy.json
  steps/representative/representative-international-details/content.en.json
  steps/representative/representative-international-details/template.html
  test/unit/steps/identity/appellant-ibca-reference/AppellantIBCAReference.test.js
  test/unit/steps/identity/appellant-name/AppellantName.test.js
  test/unit/steps/representative/representative-details/RepresentativeDetails.test.js
  test/unit/steps/representative/representative-international-details/RepresentativeInternationalDetails.test.js
Labels: ns:sscs, prd:sscs

#1599 Add hints for port of address and other reasons for appealing.
  steps/identity/appellant-international-contact-details/content.en.json
  steps/identity/appellant-international-contact-details/template.html
  steps/reasons-for-appealing/other-reasons-for-appealing/content.en.json
  steps/reasons-for-appealing/other-reasons-for-appealing/template.html
  views/components/fields.njk
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1599
