Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2025-02, with the labels that each got.

#1604 SSCSCI-1172: SYA : MVP - IBCA E2E Journey To Create a Case
  package.json
  test/e2e/data.ibca.cy.json
  test/e2e/data.ibca.en.json
  test/e2e/e2e-playwright-structure-bp/factory/pageFactory.ts
  test/e2e/e2e-playwright-structure-bp/pages/appellant-in-mainland-uk.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/appellant-text-reminders.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/check-mrn-date.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/check-your-appeal.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/confirmation.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/create-account.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-contact-details.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-dob.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-ibca-reference.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-name.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-role.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/evidence-provide.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/ibca-base.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/independence.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/index.ts
  test/e2e/e2e-playwright-structure-bp/pages/language-preference.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/mrn-date.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/other-reason-for-appealing.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/reasons-for-appealing.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/representative.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/review-decision-notice.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/the-hearing.page.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-intime.test.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-outoftime.test.ts
  test/e2e/e2e-playwright-structure-bp/utils/DateUtil.ts
  test/e2e/e2e-playwright-structure-bp/utils/JsonUtil.ts
  test/e2e/playwright.config.js
  urls.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1604

#1607 using axe instead of a11y
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  test/accessibility/a11y.js
  test/accessibility/testApp.js
  test/e2e/helpers/accessibilityHelper.js
  test/e2e/playwright.config.js
  test/e2e/smoke/accessibility.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1607

#1597 Sscsci 1452: hearings page update
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  steps/hearing/options/HearingOptions.js
  steps/hearing/options/content.cy.json
  steps/hearing/options/content.en.json
  steps/hearing/options/template.html
  steps/hearing/the-hearing/TheHearing.js
  steps/hearing/the-hearing/content.cy.json
  steps/hearing/the-hearing/content.en.json
  steps/hearing/the-hearing/template.html
  test/unit/steps/hearing/options/HearingOptions.test.js
  test/unit/steps/hearing/the-hearing/TheHearing.test.js
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1597

#1608 SSCSCI-1623: AzureRM bump to 4.15.0
  README.md
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  package.json
  test/e2e/smoke/accessibility.test.js
Labels: ns:sscs, prd:sscs, aat/add-or-update, prod/add-or-update, rel:sscs-tribunals-frontend-pr-1608

#1603 SSCSCI-1567: Accessibility name change link fix and headings
  steps/appointee/appointee-contact-details/answer.html
  steps/appointee/appointee-contact-details/content.cy.json
  steps/appointee/appointee-contact-details/content.en.json
  steps/appointee/appointee-dob/content.cy.json
  steps/appointee/appointee-dob/content.en.json
  steps/appointee/appointee-name/content.cy.json
  steps/appointee/appointee-name/content.en.json
  steps/check-your-appeal/template.html
  steps/compliance/mrn-date/template.html
  steps/hearing/arrangements/answer.html
  steps/hearing/options/answer.html
  steps/hearing/the-hearing/template.html
  steps/identity/appellant-contact-details/answer.html
  steps/identity/appellant-international-contact-details/answer.html
  steps/reasons-for-appealing/evidence-upload/template.html
  steps/reasons-for-appealing/reason-for-appealing/ReasonForAppealing.js
  steps/reasons-for-appealing/reason-for-appealing/answer.html
  steps/representative/representative-details/answer.html
  steps/representative/representative-international-details/answer.html
  views/components/fields.njk
  views/components/header.njk
  views/layouts/check_your_answers.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, test-suite:preview-regression, rel:sscs-tribunals-frontend-pr-1603

#1616 Sscsci 1612 iba accessibility aria label
  assets/js/add-reason.js
  assets/js/main.js
  steps/appointee/appointee-contact-details/template.html
  steps/appointee/appointee-name/template.html
  steps/check-your-appeal/template.html
  steps/hearing/arrangements/template.html
  steps/hearing/options/template.html
  steps/identity/appellant-contact-details/template.html
  steps/identity/appellant-ibca-reference/template.html
  steps/identity/appellant-international-contact-details/template.html
  steps/identity/appellant-name/template.html
  steps/identity/appellant-nino/template.html
  steps/reasons-for-appealing/reason-for-appealing/template.html
  steps/representative/representative-details/template.html
  steps/representative/representative-international-details/template.html
  steps/sms-notify/enter-mobile/template.html
  steps/start/benefit-type/template.html
  steps/start/postcode-checker/template.html
  views/components/common/textInput.njk
  views/components/fields.njk
  views/layouts/add_another.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1616

#1617 SSCSCI-1738
  assets/js/delete-warning.js
  assets/js/main.js
  assets/scss/main.scss
  middleware/draftAppealStoreMiddleware.js
  paths.js
  steps.js
  steps/delete-appeal/DeleteAppeal.js
  steps/draft-appeals/content.cy.json
  steps/draft-appeals/content.en.json
  steps/draft-appeals/template.html
  test/e2e/journeys/citizenDeleteCase.en.test.js
  test/e2e/page-objects/cya/checkYourAppeal.js
  test/e2e/page-objects/draft-appeals/draft-appeals-page.js
  test/e2e/smoke/accessibility.test.js
  test/unit/middleware/draftAppealStoreMiddleware.test.js
  test/unit/steps/archive-appeal/DeleteAppeal.test.js
  views/components/delete-warning.html
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1617
