Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2025-04, with the labels that each got.

#1631 ibca-test-fixes
  test/e2e/e2e-playwright-structure-bp/utils/DateUtil.ts
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1631

#1637 SSCSCI: cookie bump to 0.7.2
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1637

#1711 Revert "Update dependency applicationinsights to v2.9.6 (#1657)"
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tribunals-frontend-pr-1711

#1712 AppInsights bump
  charts/sscs-tribunals-frontend/Chart.yaml
  charts/sscs-tribunals-frontend/values.preview.template.yaml
  charts/sscs-tribunals-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  logger.js
  package.json
  services/setupSecrets.js
  test/unit/steps/logger.test.js
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1712
