Repository hmcts/sscs-submit-your-appeal, pull requests merged in 2025-03, with the labels that each got.

#1625 update welsh test
  test/e2e/page-objects/draft-appeals/draft-appeals-page.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1625

#1626 SSCSCI-370
  .dockerignore
  .nycrc
  gulpfile.js
  sonar-project.properties
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1626

#1627 update babel helpers/runtime
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, enable_keep_helm, test-suite:preview-regression, rel:sscs-tribunals-frontend-pr-1627

#1620 Iba changes to master
  test/e2e/data.ibca.cy.json
  test/e2e/data.ibca.en.json
  test/e2e/e2e-playwright-structure-bp/factory/pageFactory.ts
  test/e2e/e2e-playwright-structure-bp/pages/appellant-in-mainland-uk.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/appellant-text-reminders.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/check-mrn-date.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/check-your-appeal.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/confirmation.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/create-account.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/draft-appeals.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-contact-details.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-dob.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-ibca-reference.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-name.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/enter-appellant-role.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/evidence-provide.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/ibca-base.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/independence.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/index.ts
  test/e2e/e2e-playwright-structure-bp/pages/language-preference.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/mrn-date.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/other-reason-for-appealing.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/reasons-for-appealing.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/representative.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/review-decision-notice.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/the-hearing.page.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-intime.test.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-outoftime.test.ts
  test/e2e/e2e-playwright-structure-bp/utils/DateUtil.ts
  test/e2e/e2e-playwright-structure-bp/utils/JsonUtil.ts
  test/e2e/playwright.config.js
  urls.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1620

#1630 ibca-test-fixes
  Jenkinsfile_nightly
  test/e2e/e2e-playwright-structure-bp/pages/check-mrn-date.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/draft-appeals.page.ts
  test/e2e/e2e-playwright-structure-bp/pages/ibca-base.page.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-intime.test.ts
  test/e2e/e2e-playwright-structure-bp/tests/ibca/ibca-sya-outoftime.test.ts
  test/e2e/playwright.config.js
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-frontend-pr-1630
